// src/pug/docs-demos/vue/gauge.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Gauge"></f7-navbar>

        <f7-block strong class="text-align-center">
          <f7-gauge
            type="circle"
            :value="gaugeValue"
            :size="250"
            border-color="#2196f3"
            :border-width="10"
            :value-text="`${gaugeValue * 100}%`"
            :value-font-size="41"
            value-text-color="#2196f3"
            label-text="amount of something"
          ></f7-gauge>
          <f7-segmented tag="p" raised>
            <f7-button @click="() => gaugeValue = 0">0%</f7-button>
            <f7-button @click="() => gaugeValue = 0.25">25%</f7-button>
            <f7-button @click="() => gaugeValue = 0.5">50%</f7-button>
            <f7-button @click="() => gaugeValue = 0.75">75%</f7-button>
            <f7-button @click="() => gaugeValue = 1">100%</f7-button>
          </f7-segmented>
        </f7-block>

        <f7-block-title>Circle Gauges</f7-block-title>
        <f7-block strong>
          <f7-row>
            <f7-col class="text-align-center">
              <f7-gauge
                type="circle"
                :value="0.44"
                value-text="44%"
                value-text-color="#ff9800"
                border-color="#ff9800"
              ></f7-gauge>
            </f7-col>
            <f7-col class="text-align-center">
              <f7-gauge
                type="circle"
                :value="0.12"
                value-text="$120"
                value-text-color="#4caf50"
                border-color="#4caf50"
                label-text="of $1000 budget"
                label-text-color="#f44336"
                :label-font-weight="700"
              ></f7-gauge>
            </f7-col>
          </f7-row>
        </f7-block>
        <f7-block-title>Semicircle Gauges</f7-block-title>
        <f7-block strong>
          <f7-row>
            <f7-col class="text-align-center">
              <f7-gauge
                type="semicircle"
                :value="0.3"
                value-text="30%"
                value-text-color="#f44336"
                border-color="#f44336"
              ></f7-gauge>
            </f7-col>
            <f7-col class="text-align-center">
              <f7-gauge
                type="semicircle"
                :value="0.5"
                value-text="30kg"
                value-text-color="#e91e63"
                border-color="#e91e63"
                label-text="of 60kg total"
                label-text-color="#333"
              ></f7-gauge>
            </f7-col>
          </f7-row>
        </f7-block>
        <f7-block-title>Customization</f7-block-title>
        <f7-block strong>
          <f7-row>
            <f7-col class="text-align-center">
              <f7-gauge
                type="circle"
                :value="0.35"
                value-text="35%"
                value-text-color="#4caf50"
                :valueFontSize="51"
                :valueFontWeight="700"
                :border-width="20"
                border-color="#4caf50"
                border-bg-color="#ffeb3b"
                bg-color="#ffeb3b"
              ></f7-gauge>
            </f7-col>
            <f7-col class="text-align-center">
              <f7-gauge
                type="circle"
                :value="0.67"
                value-text="$670"
                value-text-color="#000"
                border-color="#ff9800"
                label-text="of $1000 spent"
                label-text-color="#4caf50"
                :label-font-weight="800"
                :label-font-size="12"
                :border-width="30"
              ></f7-gauge>
            </f7-col>
          </f7-row>
          <br />
          <f7-row>
            <f7-col class="text-align-center">
              <f7-gauge
                type="semicircle"
                :value="0.5"
                value-text="50%"
                value-text-color="#ffeb3b"
                :valueFontSize="41"
                :valueFontWeight="700"
                :border-width="10"
                border-color="#ffeb3b"
                border-bg-color="transparent"
              ></f7-gauge>
            </f7-col>
            <f7-col class="text-align-center">
              <f7-gauge
                type="semicircle"
                :value="0.77"
                border-color="#ff9800"
                label-text="$770 spent so far"
                label-text-color="#ff9800"
                :label-font-weight="800"
                :label-font-size="12"
                :border-width="10"
              ></f7-gauge>
            </f7-col>
          </f7-row>
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>

<script>
  export default {
    data() {
      return {
        gaugeValue: 0.5,
      };
    },
  }
</script>

// src/pug/docs-demos/svelte/gauge.svelte
<App>
  <View main>
    <Page>
      <Navbar title="Gauge"></Navbar>
      <Block strong>
        <p>Framework7 comes with Gauge component. It produces nice looking fully responsive SVG gauges.</p>
      </Block>
      <Block strong class="text-align-center">
        <Gauge
          type="circle"
          value={gaugeValue}
          size={250}
          borderColor="#2196f3"
          borderWidth={10}
          valueText={`${gaugeValue * 100}%`}
          valueFontSize={41}
          valueTextColor="#2196f3"
          labelText="amount of something"
        />
        <Segmented tag="p" raised>
          <Button onClick={() => gaugeValue = 0 }>0%</Button>
          <Button onClick={() => gaugeValue = 0.25 }>25%</Button>
          <Button onClick={() => gaugeValue = 0.5 }>50%</Button>
          <Button onClick={() => gaugeValue = 0.75 }>75%</Button>
          <Button onClick={() => gaugeValue = 1 }>100%</Button>
        </Segmented>
      </Block>

      <BlockTitle>Circle Gauges</BlockTitle>
      <Block strong>
        <Row>
          <Col class="text-align-center">
            <Gauge
              type="circle"
              value={0.44}
              valueText="44%"
              valueTextColor="#ff9800"
              borderColor="#ff9800"
            />
          </Col>
          <Col class="text-align-center">
            <Gauge
              type="circle"
              value={0.12}
              valueText="$120"
              valueTextColor="#4caf50"
              borderColor="#4caf50"
              labelText="of $1000 budget"
              labelTextColor="#f44336"
              labelFontWeight={700}
            />
          </Col>
        </Row>
      </Block>
      <BlockTitle>Semicircle Gauges</BlockTitle>
      <Block strong>
        <Row>
          <Col class="text-align-center">
            <Gauge
              type="semicircle"
              value={0.3}
              valueText="30%"
              valueTextColor="#f44336"
              borderColor="#f44336"
            />
          </Col>
          <Col class="text-align-center">
            <Gauge
              type="semicircle"
              value={0.5}
              valueText="30kg"
              valueTextColor="#e91e63"
              borderColor="#e91e63"
              labelText="of 60kg total"
              labelTextColor="#333"
            />
          </Col>
        </Row>
      </Block>
      <BlockTitle>Customization</BlockTitle>
      <Block strong>
        <Row>
          <Col class="text-align-center">
            <Gauge
              type="circle"
              value={0.35}
              valueText="35%"
              valueTextColor="#4caf50"
              valueFontSize={51}
              valueFontWeight={700}
              borderWidth={20}
              borderColor="#4caf50"
              borderBgColor="#ffeb3b"
              bgColor="#ffeb3b"
            />
          </Col>
          <Col class="text-align-center">
            <Gauge
              type="circle"
              value={0.67}
              valueText="$670"
              valueTextColor="#000"
              borderColor="#ff9800"
              labelText="of $1000 spent"
              labelTextColor="#4caf50"
              labelFontWeight={800}
              labelFontSize={12}
              borderWidth={30}
            />
          </Col>
        </Row>
        <br />
        <Row>
          <Col class="text-align-center">
            <Gauge
              type="semicircle"
              value={0.5}
              valueText="50%"
              valueTextColor="#ffeb3b"
              valueFontSize={41}
              valueFontWeight={700}
              borderWidth={10}
              borderColor="#ffeb3b"
              borderBgColor="transparent"
            />
          </Col>
          <Col class="text-align-center">
            <Gauge
              type="semicircle"
              value={0.77}
              borderColor="#ff9800"
              labelText="$770 spent so far"
              labelTextColor="#ff9800"
              labelFontWeight={800}
              labelFontSize={12}
              borderWidth={10}
            />
          </Col>
        </Row>
      </Block>
    </Page>
  </View>
</App>

<script>
  import {App, View, Page, Navbar, Block, Gauge, Segmented, Button, BlockTitle, Row, Col} from 'framework7-svelte';

  let gaugeValue = 0.5;
</script>
