// src/pug/docs-demos/vue/list-view.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="List View"></f7-navbar>
        <f7-block-title>Simple List</f7-block-title>
        <f7-list simple-list>
          <f7-list-item title="Item 1"></f7-list-item>
          <f7-list-item title="Item 2"></f7-list-item>
          <f7-list-item title="Item 3"></f7-list-item>
        </f7-list>
        <f7-block-title>Simple Links List</f7-block-title>
        <f7-list>
          <f7-list-item title="Link 1" link="#"></f7-list-item>
          <f7-list-item title="Link 2" link="#"></f7-list-item>
          <f7-list-item title="Link 3" link="#"></f7-list-item>
        </f7-list>
        <f7-block-title>Data list, with icons</f7-block-title>
        <f7-list>
          <f7-list-item title="Ivan Petrov" after="CEO">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item title="John Doe" badge="5">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item title="Jenna Smith">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
        </f7-list>
        <f7-block-title>Links</f7-block-title>
        <f7-list>
          <f7-list-item link="#" title="Ivan Petrov" after="CEO">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" title="John Doe" after="Cleaner">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" title="Jenna Smith">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
        </f7-list>
        <f7-block-title>Links, Header, Footer</f7-block-title>
        <f7-list>
          <f7-list-item link="#" header="Name" title="John Doe" after="Edit">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" header="Phone" title="+7 90 111-22-3344" after="Edit">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" header="Email" title="john@doe" footer="Home" after="Edit">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" header="Email" title="john@framework7" footer="Work" after="Edit">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
        </f7-list>
        <f7-block-title>Links, no icons</f7-block-title>
        <f7-list>
          <f7-list-item link="#" title="Ivan Petrov"></f7-list-item>
          <f7-list-item link="#" title="John Doe"></f7-list-item>
          <f7-list-item divider title="Divider Here"></f7-list-item>
          <f7-list-item link="#" title="Ivan Petrov"></f7-list-item>
          <f7-list-item link="#" title="Jenna Smith"></f7-list-item>
        </f7-list>
        <f7-block-title>Grouped with sticky titles</f7-block-title>
        <f7-list>
          <f7-list-group>
            <f7-list-item title="A" group-title></f7-list-item>
            <f7-list-item title="Aaron "></f7-list-item>
            <f7-list-item title="Abbie"></f7-list-item>
            <f7-list-item title="Adam"></f7-list-item>
          </f7-list-group>
          <f7-list-group>
            <f7-list-item title="B" group-title></f7-list-item>
            <f7-list-item title="Bailey"></f7-list-item>
            <f7-list-item title="Barclay"></f7-list-item>
            <f7-list-item title="Bartolo"></f7-list-item>
          </f7-list-group>
          <f7-list-group>
            <f7-list-item title="C" group-title></f7-list-item>
            <f7-list-item title="Caiden"></f7-list-item>
            <f7-list-item title="Calvin"></f7-list-item>
            <f7-list-item title="Candy"></f7-list-item>
          </f7-list-group>
        </f7-list>
        <f7-block-title>Mixed and nested</f7-block-title>
        <f7-list>
          <f7-list-item link="#" title="Ivan Petrov" after="CEO">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" title="Two icons here">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item title="No icons here"></f7-list-item>
          <li>
            <ul>
              <f7-list-item link="#" title="Ivan Petrov" after="CEO">
                <template #media>
                  <f7-icon icon="demo-list-icon"></f7-icon>
                </template>
              </f7-list-item>
              <f7-list-item link="#" title="Two icons here">
                <template #media>
                  <f7-icon icon="demo-list-icon"></f7-icon>
                  <f7-icon icon="demo-list-icon"></f7-icon>
                </template>
              </f7-list-item>
              <f7-list-item title="No icons here"></f7-list-item>
              <f7-list-item link="#" title="Ultra long text goes here, no, it is really really long">
                <template #media>
                  <f7-icon icon="demo-list-icon"></f7-icon>
                </template>
              </f7-list-item>
              <f7-list-item title="With toggle">
                <template #media>
                  <f7-icon icon="demo-list-icon"></f7-icon>
                </template>

                <template #after>
                  <f7-toggle></f7-toggle>
                </template>
              </f7-list-item>
            </ul>
          </li>
          <f7-list-item link="#" title="Ultra long text goes here, no, it is really really long">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item title="With toggle">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
            <template #after>
              <f7-toggle></f7-toggle>
            </template>
          </f7-list-item>
        </f7-list>
        <f7-block-title>Mixed, inset</f7-block-title>
        <f7-list>
          <f7-list-item link="#" title="Ivan Petrov" after="CEO">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" title="Two icons here">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" title="Ultra long text goes here, no, it is really really long">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item title="With toggle">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
            <template #after>
              <f7-toggle></f7-toggle>
            </template>
          </f7-list-item>
          <f7-block-footer>
            <p>Here comes some useful information about list above</p>
          </f7-block-footer>
        </f7-list>
        <f7-block-title>Tablet inset</f7-block-title>
        <f7-list medium-inset>
          <f7-list-item link="#" title="Ivan Petrov" after="CEO">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" title="Two icons here">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-list-item link="#" title="Ultra long text goes here, no, it is really really long">
            <template #media>
              <f7-icon icon="demo-list-icon"></f7-icon>
            </template>
          </f7-list-item>
          <f7-block-footer>
            <p>This list block will look like "inset" only on tablets (iPad)</p>
          </f7-block-footer>
        </f7-list>

        <f7-block-title>Media Lists</f7-block-title>
        <f7-block>
          <p>Media Lists are almost the same as Data Lists, but with a more flexible layout for visualization of more complex data, like products, services, users, etc.</p>
        </f7-block>
        <f7-block-title>Songs</f7-block-title>
        <f7-list media-list>
          <f7-list-item
            link="#"
            title="Yellow Submarine"
            after="$15"
            subtitle="Beatles"
            text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
          >
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-160x160-1.jpg" width="80" />
            </template>
          </f7-list-item>
          <f7-list-item
            link="#"
            title="Don't Stop Me Now"
            after="$22"
            subtitle="Queen"
            text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
          >
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-160x160-2.jpg" width="80" />
            </template>
          </f7-list-item>
          <f7-list-item
            link="#"
            title="Billie Jean"
            after="$16"
            subtitle="Michael Jackson"
            text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
          >
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-160x160-3.jpg" width="80" />
            </template>
          </f7-list-item>
        </f7-list>
        <f7-block-title>Mail App</f7-block-title>
        <f7-list media-list>
          <f7-list-item
            link="#"
            title="Facebook"
            after="17:14"
            subtitle="New messages from John Doe"
            text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
          ></f7-list-item>
          <f7-list-item
            link="#"
            title="John Doe (via Twitter)"
            after="17:11"
            subtitle="John Doe (@_johndoe) mentioned you on Twitter!"
            text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
          ></f7-list-item>
          <f7-list-item
            link="#"
            title="Facebook"
            after="16:48"
            subtitle="New messages from John Doe"
            text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
          ></f7-list-item>
          <f7-list-item
            link="#"
            title="John Doe (via Twitter)"
            after="15:32"
            subtitle="John Doe (@_johndoe) mentioned you on Twitter!"
            text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
          ></f7-list-item>
        </f7-list>
        <f7-block-title>Something more simple</f7-block-title>
        <f7-list media-list>
          <f7-list-item
            title="Yellow Submarine"
            subtitle="Beatles">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/fashion-88x88-1.jpg" width="44" />
            </template>
          </f7-list-item>
          <f7-list-item
            link="#"
            title="Don't Stop Me Now"
            subtitle="Queen">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/fashion-88x88-2.jpg" width="44" />
            </template>
          </f7-list-item>
          <f7-list-item
            title="Billie Jean"
            subtitle="Michael Jackson">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/fashion-88x88-3.jpg" width="44" />
            </template>
          </f7-list-item>
        </f7-list>
        <f7-block-title>Inset</f7-block-title>
        <f7-list media-list inset>
          <f7-list-item
            link="#"
            title="Yellow Submarine"
            subtitle="Beatles">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/fashion-88x88-4.jpg" width="44" />
            </template>
          </f7-list-item>
          <f7-list-item
            link="#"
            title="Don't Stop Me Now"
            subtitle="Queen">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/fashion-88x88-5.jpg" width="44" />
            </template>
          </f7-list-item>
          <f7-list-item
            link="#"
            title="Billie Jean"
            subtitle="Michael Jackson">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/fashion-88x88-6.jpg" width="44" />
            </template>
          </f7-list-item>
        </f7-list>
      </f7-page>
    </f7-view>
  </f7-app>
</template>

<style>
    .demo-list-icon, .icon-f7 {
      background: #ccc;
      display: block;
      position: relative;
    }
    .ios .demo-list-icon, .ios .icon-f7, .ios .icon-vi {
      width: 29px;
      height: 29px;
      border-radius: 6px;
      box-sizing: border-box;
    }
    .md .demo-list-icon, .md .icon-f7, .md .icon-vi {
      width: 24px;
      height: 24px;
      border-radius: 4px;
    }
    .aurora .demo-list-icon, .aurora .icon-f7, .aurora .icon-vi {
      width: 18px;
      height: 18px;
      border-radius: 4px;
    }
</style>

// src/pug/docs-demos/svelte/list-view.svelte
<App>
  <View main>
    <Page>
      <Navbar title="List View"></Navbar>
      <BlockTitle>Simple List</BlockTitle>
      <List simpleList>
        <ListItem title="Item 1"></ListItem>
        <ListItem title="Item 2"></ListItem>
        <ListItem title="Item 3"></ListItem>
      </List>
      <BlockTitle>Simple Links List</BlockTitle>
      <List>
        <ListItem title="Link 1" link="#"></ListItem>
        <ListItem title="Link 2" link="#"></ListItem>
        <ListItem title="Link 3" link="#"></ListItem>
      </List>
      <BlockTitle>Data list, with icons</BlockTitle>
      <List>
        <ListItem title="Ivan Petrov" after="CEO">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem title="John Doe" badge="5">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem title="Jenna Smith">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
      </List>
      <BlockTitle>Links</BlockTitle>
      <List>
        <ListItem link="#" title="Ivan Petrov" after="CEO">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" title="John Doe" after="Cleaner">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" title="Jenna Smith">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
      </List>
      <BlockTitle>Links, Header, Footer</BlockTitle>
      <List>
        <ListItem link="#" header="Name" title="John Doe" after="Edit">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" header="Phone" title="+7 90 111-22-3344" after="Edit">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" header="Email" title="john@doe" footer="Home" after="Edit">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" header="Email" title="john@framework7" footer="Work" after="Edit">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
      </List>
      <BlockTitle>Links, no icons</BlockTitle>
      <List>
        <ListItem link="#" title="Ivan Petrov"></ListItem>
        <ListItem link="#" title="John Doe"></ListItem>
        <ListItem divider title="Divider Here"></ListItem>
        <ListItem link="#" title="Ivan Petrov"></ListItem>
        <ListItem link="#" title="Jenna Smith"></ListItem>
      </List>
      <BlockTitle>Grouped with sticky titles</BlockTitle>
      <List ul={false}>
        <ListGroup>
          <ListItem title="A" groupTitle></ListItem>
          <ListItem title="Aaron "></ListItem>
          <ListItem title="Abbie"></ListItem>
          <ListItem title="Adam"></ListItem>
        </ListGroup>
        <ListGroup>
          <ListItem title="B" groupTitle></ListItem>
          <ListItem title="Bailey"></ListItem>
          <ListItem title="Barclay"></ListItem>
          <ListItem title="Bartolo"></ListItem>
        </ListGroup>
        <ListGroup>
          <ListItem title="C" groupTitle></ListItem>
          <ListItem title="Caiden"></ListItem>
          <ListItem title="Calvin"></ListItem>
          <ListItem title="Candy"></ListItem>
        </ListGroup>
      </List>
      <BlockTitle>Mixed and nested</BlockTitle>
      <List>
        <ListItem link="#" title="Ivan Petrov" after="CEO">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" title="Two icons here">
          <i slot="media" class="icon demo-list-icon" />
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem title="No icons here"></ListItem>
        <li>
          <ul>
            <ListItem link="#" title="Ivan Petrov" after="CEO">
              <i slot="media" class="icon demo-list-icon" />
            </ListItem>
            <ListItem link="#" title="Two icons here">
              <i slot="media" class="icon demo-list-icon" />
              <i slot="media" class="icon demo-list-icon" />
            </ListItem>
            <ListItem title="No icons here"></ListItem>
            <ListItem link="#" title="Ultra long text goes here, no, it is really really long">
              <i slot="media" class="icon demo-list-icon" />
            </ListItem>
            <ListItem title="With toggle">
              <i slot="media" class="icon demo-list-icon" />
              <span slot="after">
                <Toggle />
              </span>
            </ListItem>
          </ul>
        </li>
        <ListItem link="#" title="Ultra long text goes here, no, it is really really long">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem title="With toggle">
          <i slot="media" class="icon demo-list-icon" />
          <span slot="after">
            <Toggle />
          </span>
        </ListItem>
      </List>
      <BlockTitle>Mixed, inset</BlockTitle>
      <List>
        <ListItem link="#" title="Ivan Petrov" after="CEO">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" title="Two icons here">
          <i slot="media" class="icon demo-list-icon" />
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" title="Ultra long text goes here, no, it is really really long">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem title="With toggle">
          <i slot="media" class="icon demo-list-icon" />
          <span slot="after">
            <Toggle />
          </span>
        </ListItem>
        <div class="block-footer" slot="after-list">
          <p>Here comes some useful information about list above</p>
        </div>
      </List>
      <BlockTitle>Tablet inset</BlockTitle>
      <List mediumInset>
        <ListItem link="#" title="Ivan Petrov" after="CEO">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" title="Two icons here">
          <i slot="media" class="icon demo-list-icon" />
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <ListItem link="#" title="Ultra long text goes here, no, it is really really long">
          <i slot="media" class="icon demo-list-icon" />
        </ListItem>
        <div class="block-footer" slot="after-list">
          <p>This list block will look like "inset" only on tablets (iPad)</p>
        </div>
      </List>

      <BlockTitle>Media Lists</BlockTitle>
      <Block>
        <p>Media Lists are almost the same as Data Lists, but with a more flexible layout for visualization of more complex data, like products, services, users, etc.</p>
      </Block>
      <BlockTitle>Songs</BlockTitle>
      <List mediaList>
        <ListItem
          link="#"
          title="Yellow Submarine"
          after="$15"
          subtitle="Beatles"
          text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
        >
          <img slot="media" src="https://cdn.framework7.io/placeholder/people-160x160-1.jpg" width="80" />
        </ListItem>
        <ListItem
          link="#"
          title="Don't Stop Me Now"
          after="$22"
          subtitle="Queen"
          text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
        >
          <img slot="media" src="https://cdn.framework7.io/placeholder/people-160x160-2.jpg" width="80" />
        </ListItem>
        <ListItem
          link="#"
          title="Billie Jean"
          after="$16"
          subtitle="Michael Jackson"
          text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
        >
          <img slot="media" src="https://cdn.framework7.io/placeholder/people-160x160-3.jpg" width="80" />
        </ListItem>
      </List>
      <BlockTitle>Mail App</BlockTitle>
      <List mediaList>
        <ListItem
          link="#"
          title="Facebook"
          after="17:14"
          subtitle="New messages from John Doe"
          text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
        ></ListItem>
        <ListItem
          link="#"
          title="John Doe (via Twitter)"
          after="17:11"
          subtitle="John Doe (@_johndoe) mentioned you on Twitter!"
          text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
        ></ListItem>
        <ListItem
          link="#"
          title="Facebook"
          after="16:48"
          subtitle="New messages from John Doe"
          text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
        ></ListItem>
        <ListItem
          link="#"
          title="John Doe (via Twitter)"
          after="15:32"
          subtitle="John Doe (@_johndoe) mentioned you on Twitter!"
          text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
        ></ListItem>
      </List>
      <BlockTitle>Something more simple</BlockTitle>
      <List mediaList>
        <ListItem
          title="Yellow Submarine"
          subtitle="Beatles">
          <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-88x88-1.jpg" width="44" />
        </ListItem>
        <ListItem
          link="#"
          title="Don't Stop Me Now"
          subtitle="Queen">
          <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-88x88-2.jpg" width="44" />
        </ListItem>
        <ListItem
          title="Billie Jean"
          subtitle="Michael Jackson">
          <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-88x88-3.jpg" width="44" />
        </ListItem>
      </List>
      <BlockTitle>Inset</BlockTitle>
      <List mediaList inset>
        <ListItem
          link="#"
          title="Yellow Submarine"
          subtitle="Beatles">
          <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-88x88-4.jpg" width="44" />
        </ListItem>
        <ListItem
          link="#"
          title="Don't Stop Me Now"
          subtitle="Queen">
          <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-88x88-5.jpg" width="44" />
        </ListItem>
        <ListItem
          link="#"
          title="Billie Jean"
          subtitle="Michael Jackson">
          <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-88x88-6.jpg" width="44" />
        </ListItem>
      </List>
    </Page>
  </View>
</App>
<style>
  :global(.demo-list-icon, .icon-f7) {
    background: #ccc;
    display: block;
    position: relative;
  }
  :global(.ios .demo-list-icon, .ios .icon-f7, .ios .icon-vi) {
    width: 29px;
    height: 29px;
    border-radius: 6px;
    box-sizing: border-box;
  }
  :global(.md .demo-list-icon, .md .icon-f7, .md .icon-vi) {
    width: 24px;
    height: 24px;
    border-radius: 4px;
  }
  :global(.aurora .demo-list-icon, .aurora .icon-f7, .aurora .icon-vi) {
    width: 18px;
    height: 18px;
    border-radius: 4px;
  }
</style>
<script>
  import {App, View, Page, Navbar, BlockTitle, List, ListItem, Icon, ListGroup, Toggle, BlockFooter, Block} from 'framework7-svelte';
</script>
