// src/pug/docs-demos/react/login-screen.jsx
import React from 'react';
import { App, View } from 'framework7-react';

import LoginScreenPage from './login-screen_page.jsx';
import LoginScreenMain from './login-screen_main.jsx';

export default () => (
  <App
    routes={[
      {
        path: '/',
        component: LoginScreenMain,
      },
      {
        path: '/login-screen-page/',
        component: LoginScreenPage,
      },
    ]}
  >
    <View main url="/" />
  </App>
);

// src/pug/docs-demos/svelte/login-screen.svelte
<App routes={routes}>
  <View main url="/" />
</App>

<script>
  import {f7, App, View} from 'framework7-svelte';

  import LoginScreenMain from './login-screen_main.svelte';
  import LoginScreenPage from './login-screen_page.svelte';

  const routes = [
    {
      path: '/',
      component: LoginScreenMain,
    },
    {
      path: '/login-screen-page/',
      component: LoginScreenPage,
    },
  ];
</script>
