// src/pug/docs-demos/vue/menu-list.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Menu List" />

        <f7-block strong>
          <p>
            Menu list unlike usual links list is designed to indicate currently active screen (or
            section) of your app. Think about it like a Tabbar but in a form of a list.
          </p>
        </f7-block>

        <f7-list menu-list>
          <f7-list-item
            link
            title="Home"
            :selected="selected === 'home'"
            @click="() => (selected = 'home')"
          >
            <template #media>
              <f7-icon md="material:home" aurora="f7:house_fill" ios="f7:house_fill" />
            </template>
          </f7-list-item>
          <f7-list-item
            link
            title="Profile"
            :selected="selected === 'profile'"
            @click="() => (selected = 'profile')"
          >
            <template #media>
              <f7-icon md="material:person" aurora="f7:person_fill" ios="f7:person_fill" />
            </template>
          </f7-list-item>
          <f7-list-item
            link
            title="Settings"
            :selected="selected === 'settings'"
            @click="() => (selected = 'settings')"
          >
            <template #media>
              <f7-icon md="material:settings" aurora="f7:gear_alt_fill" ios="f7:gear_alt_fill" />
            </template>
          </f7-list-item>
        </f7-list>

        <f7-list menu-list media-list>
          <f7-list-item
            link
            title="Home"
            subtitle="Home subtitle"
            :selected="selectedMedia === 'home'"
            @click="() => (selectedMedia = 'home')"
          >
            <template #media>
              <f7-icon md="material:home" aurora="f7:house_fill" ios="f7:house_fill" />
            </template>
          </f7-list-item>
          <f7-list-item
            link
            title="Profile"
            subtitle="Profile subtitle"
            :selected="selectedMedia === 'profile'"
            @click="() => (selectedMedia = 'profile')"
          >
            <template #media>
              <f7-icon md="material:person" aurora="f7:person_fill" ios="f7:person_fill" />
            </template>
          </f7-list-item>
          <f7-list-item
            link
            title="Settings"
            subtitle="Settings subtitle"
            :selected="selectedMedia === 'settings'"
            @click="() => (selectedMedia = 'settings')"
          >
            <template #media>
              <f7-icon md="material:settings" aurora="f7:gear_alt_fill" ios="f7:gear_alt_fill" />
            </template>
          </f7-list-item>
        </f7-list>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
<script>
import { ref } from 'vue';

export default {
  setup() {
    const selected = ref('home');
    const selectedMedia = ref('home');
    return {
      selected,
      selectedMedia,
    };
  },
};
</script>

// src/pug/docs-demos/svelte/menu-list.svelte
<script>
  import { App, View, Page, Navbar, Block, List, ListItem, Icon } from 'framework7-svelte';

  let selected = 'home';
  let selectedMedia = 'home';
</script>
<App>
  <View main>
    <Page>
      <Navbar title="Menu List" />

      <Block strong>
        <p>
          Menu list unlike usual links list is designed to indicate currently active screen (or section)
          of your app. Think about it like a Tabbar but in a form of a list.
        </p>
      </Block>

      <List menuList>
        <ListItem link title="Home" selected={selected === 'home'} onClick={() => (selected = 'home')}>
          <span slot="media">
            <Icon md="material:home" aurora="f7:house_fill" ios="f7:house_fill" />
          </span>
        </ListItem>
        <ListItem
          link
          title="Profile"
          selected={selected === 'profile'}
          onClick={() => (selected = 'profile')}>
          <span slot="media">
            <Icon md="material:person" aurora="f7:person_fill" ios="f7:person_fill" />
          </span>
        </ListItem>
        <ListItem
          link
          title="Settings"
          selected={selected === 'settings'}
          onClick={() => (selected = 'settings')}>
          <span slot="media">
            <Icon md="material:settings" aurora="f7:gear_alt_fill" ios="f7:gear_alt_fill" />
          </span>
        </ListItem>
      </List>

      <List menuList mediaList>
        <ListItem
          link
          title="Home"
          subtitle="Home subtitle"
          selected={selectedMedia === 'home'}
          onClick={() => (selectedMedia = 'home')}>
          <span slot="media">
            <Icon md="material:home" aurora="f7:house_fill" ios="f7:house_fill" />
          </span>
        </ListItem>
        <ListItem
          link
          title="Profile"
          subtitle="Profile subtitle"
          selected={selectedMedia === 'profile'}
          onClick={() => (selectedMedia = 'profile')}>
          <span slot="media">
            <Icon md="material:person" aurora="f7:person_fill" ios="f7:person_fill" />
          </span>
        </ListItem>
        <ListItem
          link
          title="Settings"
          subtitle="Settings subtitle"
          selected={selectedMedia === 'settings'}
          onClick={() => (selectedMedia = 'settings')}>
          <span slot="media">
            <Icon md="material:settings" aurora="f7:gear_alt_fill" ios="f7:gear_alt_fill" />
          </span>
        </ListItem>
      </List>
    </Page>
  </View>
</App>
