// src/pug/docs-demos/vue/panel.vue
<template>
  <f7-app>
    <!-- Left resizable Panel with Reveal effect -->
    <f7-panel left reveal resizable>
      <f7-view>
        <f7-page>
          <f7-block>Left panel content</f7-block>
        </f7-page>
      </f7-view>
    </f7-panel>

    <!-- Right resizable Panel with Cover effect and dark layout theme -->
    <f7-panel right resizable dark>
      <f7-view>
        <f7-page>
          <f7-block>Right panel content</f7-block>
        </f7-page>
      </f7-view>
    </f7-panel>

    <f7-view main>
      <f7-page>
        <f7-navbar title="Panel"></f7-navbar>

        <f7-panel id="panel-nested" dark left cover container-el="#panel-page">
          <f7-page>
            <f7-block strong>
              <p>This is page-nested Panel.</p>
              <p>
                <f7-link panel-close>Close me</f7-link>
              </p>
            </f7-block>
          </f7-page>
        </f7-panel>

        <f7-block>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button raised fill panel-open="left"> Open left panel </f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button raised fill panel-open="right"> Open right panel </f7-button>
            </f7-col>
          </f7-row>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button raised fill panel-open="#panel-nested"> Open nested panel </f7-button>
            </f7-col>
          </f7-row>
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
<style>
/* Limit resizable panel width */
.panel {
  min-width: 100px;
  max-width: 90vw;
}
</style>

// src/pug/docs-demos/svelte/panel.svelte
<App>
  <Panel resizable left reveal>
    <View>
      <Page>
        <Block>Left panel content</Block>
      </Page>
    </View>
  </Panel>
  <Panel resizable right dark>
    <View>
      <Page>
        <Block>Right panel content</Block>
      </Page>
    </View>
  </Panel>
  <View main>
    <Page>
      <Navbar title="Panel"></Navbar>

      <Panel left cover dark containerEl="#panel-page" id="panel-nested">
        <Page>
          <Block strong>
            <p>This is page-nested Panel.</p>
            <p>
              <Link panelClose>Close me</Link>
            </p>
          </Block>
        </Page>
      </Panel>

      <Block>
        <Row tag="p">
          <Col tag="span">
            <Button raised fill panelOpen="left">
              Open left panel
            </Button>
          </Col>
          <Col tag="span">
            <Button raised fill panelOpen="right">
              Open right panel
            </Button>
          </Col>
        </Row>
        <Row tag="p">
          <Col tag="span">
            <Button raised fill panelOpen="#panel-nested">
              Open nested panel
            </Button>
          </Col>
        </Row>
      </Block>
    </Page>
  </View>
</App>
<style>
  /* Limit resizable panel width */
  :global(.panel) {
    min-width: 100px;
    max-width: 90vw;
  }
</style>
<script>
  import {App, Panel, View, Page, Block, Navbar, Col, Button, Row, Link} from 'framework7-svelte';
</script>
