// src/pug/docs-demos/react/searchbar-expandable.jsx
import React from 'react';
import {
  App,
  View,
  Page,
  Navbar,
  NavRight,
  Link,
  Searchbar,
  List,
  ListItem,
  theme,
} from 'framework7-react';

export default () => (
  <App>
    <View main>
      <Page>
        <Navbar title="Searchbar">
          <NavRight>
            <Link
              searchbarEnable=".searchbar-demo"
              iconIos="f7:search"
              iconAurora="f7:search"
              iconMd="material:search"
            ></Link>
          </NavRight>
          <Searchbar
            className="searchbar-demo"
            expandable
            searchContainer=".search-list"
            searchIn=".item-title"
            disableButton={!theme.aurora}
          ></Searchbar>
        </Navbar>
        <List className="searchbar-not-found">
          <ListItem title="Nothing found"></ListItem>
        </List>
        <List className="search-list searchbar-found">
          <ListItem title="Acura"></ListItem>
          <ListItem title="Audi"></ListItem>
          <ListItem title="BMW"></ListItem>
          <ListItem title="Cadillac "></ListItem>
          <ListItem title="Chevrolet "></ListItem>
          <ListItem title="Chrysler "></ListItem>
          <ListItem title="Dodge "></ListItem>
          <ListItem title="Ferrari "></ListItem>
          <ListItem title="Ford "></ListItem>
          <ListItem title="GMC "></ListItem>
          <ListItem title="Honda"></ListItem>
          <ListItem title="Hummer"></ListItem>
          <ListItem title="Hyundai"></ListItem>
          <ListItem title="Infiniti "></ListItem>
          <ListItem title="Isuzu "></ListItem>
          <ListItem title="Jaguar "></ListItem>
          <ListItem title="Jeep "></ListItem>
          <ListItem title="Kia"></ListItem>
          <ListItem title="Lamborghini "></ListItem>
          <ListItem title="Land Rover"></ListItem>
          <ListItem title="Lexus "></ListItem>
          <ListItem title="Lincoln "></ListItem>
          <ListItem title="Lotus "></ListItem>
          <ListItem title="Mazda"></ListItem>
          <ListItem title="Mercedes-Benz"></ListItem>
          <ListItem title="Mercury "></ListItem>
          <ListItem title="Mitsubishi"></ListItem>
          <ListItem title="Nissan "></ListItem>
          <ListItem title="Oldsmobile "></ListItem>
          <ListItem title="Peugeot "></ListItem>
          <ListItem title="Pontiac "></ListItem>
          <ListItem title="Porsche"></ListItem>
          <ListItem title="Regal"></ListItem>
          <ListItem title="Saab "></ListItem>
          <ListItem title="Saturn "></ListItem>
          <ListItem title="Subaru "></ListItem>
          <ListItem title="Suzuki "></ListItem>
          <ListItem title="Toyota"></ListItem>
          <ListItem title="Volkswagen"></ListItem>
          <ListItem title="Volvo"></ListItem>
        </List>
      </Page>
    </View>
  </App>
);

// src/pug/docs-demos/svelte/searchbar-expandable.svelte

<App>
  <View main>
    <Page>
      <Navbar title="Searchbar">
        <NavRight>
          <Link searchbarEnable=".searchbar-demo" iconIos="f7:search" iconAurora="f7:search" iconMd="material:search"></Link>
        </NavRight>
        <Searchbar
          class="searchbar-demo"
          expandable
          searchContainer=".search-list"
          searchIn=".item-title"
          disableButton={!theme.aurora}
        />
      </Navbar>
      <List class="searchbar-not-found">
        <ListItem title="Nothing found"></ListItem>
      </List>
      <List class="search-list searchbar-found">
        <ListItem title="Acura" />
        <ListItem title="Audi" />
        <ListItem title="BMW" />
        <ListItem title="Cadillac " />
        <ListItem title="Chevrolet " />
        <ListItem title="Chrysler " />
        <ListItem title="Dodge " />
        <ListItem title="Ferrari " />
        <ListItem title="Ford " />
        <ListItem title="GMC " />
        <ListItem title="Honda" />
        <ListItem title="Hummer" />
        <ListItem title="Hyundai" />
        <ListItem title="Infiniti " />
        <ListItem title="Isuzu " />
        <ListItem title="Jaguar " />
        <ListItem title="Jeep " />
        <ListItem title="Kia" />
        <ListItem title="Lamborghini " />
        <ListItem title="Land Rover" />
        <ListItem title="Lexus " />
        <ListItem title="Lincoln " />
        <ListItem title="Lotus " />
        <ListItem title="Mazda" />
        <ListItem title="Mercedes-Benz" />
        <ListItem title="Mercury " />
        <ListItem title="Mitsubishi" />
        <ListItem title="Nissan " />
        <ListItem title="Oldsmobile " />
        <ListItem title="Peugeot " />
        <ListItem title="Pontiac " />
        <ListItem title="Porsche" />
        <ListItem title="Regal" />
        <ListItem title="Saab " />
        <ListItem title="Saturn " />
        <ListItem title="Subaru " />
        <ListItem title="Suzuki " />
        <ListItem title="Toyota" />
        <ListItem title="Volkswagen" />
        <ListItem title="Volvo" />
      </List>
    </Page>
  </View>
</App>

<script>
  import {theme, App, View, Page, Navbar, NavRight, Link, Subnavbar, Searchbar, List, ListItem} from 'framework7-svelte';
</script>
