// src/pug/docs-demos/vue/swiper.vue
<template>
    <f7-app>
      <f7-view main>
        <f7-page>
          <f7-navbar title="Swiper"></f7-navbar>
          <f7-block-title>Minimal Layout</f7-block-title>
          <f7-swiper>
            <f7-swiper-slide>Slide 1</f7-swiper-slide>
            <f7-swiper-slide>Slide 2</f7-swiper-slide>
            <f7-swiper-slide>Slide 3</f7-swiper-slide>
          </f7-swiper>

          <f7-block-title>With all controls</f7-block-title>
          <f7-swiper pagination navigation scrollbar>
            <f7-swiper-slide>Slide 1</f7-swiper-slide>
            <f7-swiper-slide>Slide 2</f7-swiper-slide>
            <f7-swiper-slide>Slide 3</f7-swiper-slide>
          </f7-swiper>

          <f7-block-title>With additional parameters</f7-block-title>
          <f7-swiper navigation :params="{speed:500, slidesPerView: 3, spaceBetween: 20}">
            <f7-swiper-slide>Slide 1</f7-swiper-slide>
            <f7-swiper-slide>Slide 2</f7-swiper-slide>
            <f7-swiper-slide>Slide 3</f7-swiper-slide>
            <f7-swiper-slide>Slide 4</f7-swiper-slide>
            <f7-swiper-slide>Slide 5</f7-swiper-slide>
            <f7-swiper-slide>Slide 6</f7-swiper-slide>
          </f7-swiper>
          <f7-block></f7-block>
        </f7-page>
      </f7-view>
    </f7-app>
</template>
<style>
  .swiper-slide {
    background: #fff;
    text-align: center;
    font-size: 18px;
    line-height: 200px;
    box-sizing: border-box;
    border: 1px solid #ccc;
  }
</style>

// src/pug/docs-demos/svelte/swiper.svelte
<App>
  <View main>
    <Page>
      <Navbar title="Swiper" />
      <BlockTitle>Minimal Layout</BlockTitle>
      <Swiper>
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
        <SwiperSlide>Slide 3</SwiperSlide>
      </Swiper>

      <BlockTitle>With all controls</BlockTitle>
      <Swiper pagination navigation scrollbar>
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
        <SwiperSlide>Slide 3</SwiperSlide>
      </Swiper>

      <BlockTitle>With additional parameters</BlockTitle>
      <Swiper navigation params={{speed:500, slidesPerView: 3, spaceBetween: 20}}>
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
        <SwiperSlide>Slide 3</SwiperSlide>
        <SwiperSlide>Slide 4</SwiperSlide>
        <SwiperSlide>Slide 5</SwiperSlide>
        <SwiperSlide>Slide 6</SwiperSlide>
      </Swiper>

      <Block />
    </Page>
  </View>
</App>
<style>
  :global(.swiper-slide) {
    background: #fff;
    text-align: center;
    font-size: 18px;
    line-height: 200px;
    box-sizing: border-box;
    border: 1px solid #ccc;
  }
</style>
<script>
  import {App, View, Page, Navbar, BlockTitle, Swiper, SwiperSlide, Block} from 'framework7-svelte';
</script>
