// src/pug/docs-demos/vue/toggle.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Toggle"></f7-navbar>
        <f7-block-title>Super Heroes</f7-block-title>
        <f7-list simple-list>
          <f7-list-item>
            <span>Batman</span>
            <f7-toggle checked></f7-toggle>
          </f7-list-item>
          <f7-list-item>
            <span>Aquaman</span>
            <f7-toggle checked color="blue"></f7-toggle>
          </f7-list-item>
          <f7-list-item>
            <span>Superman</span>
            <f7-toggle checked color="red"></f7-toggle>
          </f7-list-item>
          <f7-list-item>
            <span>Hulk</span>
            <f7-toggle color="green"></f7-toggle>
          </f7-list-item>
          <f7-list-item>
            <span>Spiderman (Disabled)</span>
            <f7-toggle disabled></f7-toggle>
          </f7-list-item>
          <f7-list-item>
            <span>Ironman (Disabled)</span>
            <f7-toggle checked disabled></f7-toggle>
          </f7-list-item>
          <f7-list-item>
            <span>Thor</span>
            <f7-toggle checked color="orange"></f7-toggle>
          </f7-list-item>
          <f7-list-item>
            <span>Wonder Woman</span>
            <f7-toggle color="pink"></f7-toggle>
          </f7-list-item>
        </f7-list>
      </f7-page>
    </f7-view>
  </f7-app>
</template>

// src/pug/docs-demos/svelte/toggle.svelte

<App>
  <View main>
    <Page>
      <Navbar title="Toggle"></Navbar>
      <BlockTitle>Super Heroes</BlockTitle>
      <List simpleList>
        <ListItem>
          <span>Batman</span>
          <Toggle checked></Toggle>
        </ListItem>
        <ListItem>
          <span>Aquaman</span>
          <Toggle checked color="blue"></Toggle>
        </ListItem>
        <ListItem>
          <span>Superman</span>
          <Toggle checked color="red"></Toggle>
        </ListItem>
        <ListItem>
          <span>Hulk</span>
          <Toggle color="green"></Toggle>
        </ListItem>
        <ListItem>
          <span>Spiderman (Disabled)</span>
          <Toggle disabled></Toggle>
        </ListItem>
        <ListItem>
          <span>Ironman (Disabled)</span>
          <Toggle checked disabled></Toggle>
        </ListItem>
        <ListItem>
          <span>Thor</span>
          <Toggle checked color="orange"></Toggle>
        </ListItem>
        <ListItem>
          <span>Wonder Woman</span>
          <Toggle color="pink"></Toggle>
        </ListItem>
      </List>
    </Page>
  </View>
</App>

<script>
  import {App, View, Page, Navbar, BlockTitle, List, ListItem, Toggle} from 'framework7-svelte';
</script>
