// src/pug/docs-demos/vue/accordion.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Accordion"></f7-navbar>
        <f7-block-title>List View Accordion</f7-block-title>
        <f7-list accordion-list>
          <f7-list-item accordion-item title="Lorem Ipsum">
            <f7-accordion-content>
              <f7-block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra blandit suscipit eget ipsum.
                </p>
              </f7-block>
            </f7-accordion-content>
          </f7-list-item>
          <f7-list-item accordion-item title="Nested List">
            <f7-accordion-content>
              <f7-list>
                <f7-list-item title="Item 1"></f7-list-item>
                <f7-list-item title="Item 2"></f7-list-item>
                <f7-list-item title="Item 3"></f7-list-item>
                <f7-list-item title="Item 4"></f7-list-item>
              </f7-list>
            </f7-accordion-content>
          </f7-list-item>
          <f7-list-item accordion-item title="Integer semper">
            <f7-accordion-content>
              <f7-block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra blandit suscipit eget ipsum.
                </p>
              </f7-block>
            </f7-accordion-content>
          </f7-list-item>
        </f7-list>

        <f7-block-title>Inset Accordion</f7-block-title>
        <f7-list accordion-list inset>
          <f7-list-item accordion-item title="Lorem Ipsum">
            <f7-accordion-content>
              <f7-block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra blandit suscipit eget ipsum.
                </p>
              </f7-block>
            </f7-accordion-content>
          </f7-list-item>
          <f7-list-item accordion-item title="Nested List">
            <f7-accordion-content>
              <f7-list>
                <f7-list-item title="Item 1"></f7-list-item>
                <f7-list-item title="Item 2"></f7-list-item>
                <f7-list-item title="Item 3"></f7-list-item>
                <f7-list-item title="Item 4"></f7-list-item>
              </f7-list>
            </f7-accordion-content>
          </f7-list-item>
          <f7-list-item accordion-item title="Integer semper">
            <f7-accordion-content>
              <f7-block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra blandit suscipit eget ipsum.
                </p>
              </f7-block>
            </f7-accordion-content>
          </f7-list-item>
        </f7-list>

        <f7-block-title>Opposite Side</f7-block-title>
        <f7-list accordion-list accordion-opposite>
          <f7-list-item accordion-item title="Lorem Ipsum">
            <f7-accordion-content>
              <f7-block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra blandit suscipit eget ipsum.
                </p>
              </f7-block>
            </f7-accordion-content>
          </f7-list-item>
          <f7-list-item accordion-item title="Nested List">
            <f7-accordion-content>
              <f7-list>
                <f7-list-item title="Item 1"></f7-list-item>
                <f7-list-item title="Item 2"></f7-list-item>
                <f7-list-item title="Item 3"></f7-list-item>
                <f7-list-item title="Item 4"></f7-list-item>
              </f7-list>
            </f7-accordion-content>
          </f7-list-item>
          <f7-list-item accordion-item title="Integer semper">
            <f7-accordion-content>
              <f7-block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra blandit suscipit eget ipsum.
                </p>
              </f7-block>
            </f7-accordion-content>
          </f7-list-item>
        </f7-list>

        <f7-block-title>Custom Collapsible</f7-block-title>
        <f7-block inner accordion-list>
          <f7-accordion-item v-for="n in 3" :key="n">
            <f7-accordion-toggle><b>Item {{n}}</b></f7-accordion-toggle>
            <f7-accordion-content>Content {{n}}</f7-accordion-content>
          </f7-accordion-item>
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>

// src/pug/docs-demos/react/accordion.jsx
import React from 'react';

export default () => (
  <App>
    <View main>
      <Page>
        <Navbar title="Accordion" />
        <BlockTitle>List View Accordion</BlockTitle>
        <List accordionList>
          <ListItem accordionItem title="Lorem Ipsum">
            <AccordionContent>
              <Block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque
                  nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer
                  semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est
                  rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra
                  blandit suscipit eget ipsum.
                </p>
              </Block>
            </AccordionContent>
          </ListItem>
          <ListItem accordionItem title="Nested List">
            <AccordionContent>
              <List>
                <ListItem title="Item 1"></ListItem>
                <ListItem title="Item 2"></ListItem>
                <ListItem title="Item 3"></ListItem>
                <ListItem title="Item 4"></ListItem>
              </List>
            </AccordionContent>
          </ListItem>
          <ListItem accordionItem title="Integer semper">
            <AccordionContent>
              <Block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque
                  nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer
                  semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est
                  rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra
                  blandit suscipit eget ipsum.
                </p>
              </Block>
            </AccordionContent>
          </ListItem>
        </List>

        <BlockTitle>Inset Accordion</BlockTitle>
        <List accordionList inset>
          <ListItem accordionItem title="Lorem Ipsum">
            <AccordionContent>
              <Block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque
                  nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer
                  semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est
                  rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra
                  blandit suscipit eget ipsum.
                </p>
              </Block>
            </AccordionContent>
          </ListItem>
          <ListItem accordionItem title="Nested List">
            <AccordionContent>
              <List>
                <ListItem title="Item 1"></ListItem>
                <ListItem title="Item 2"></ListItem>
                <ListItem title="Item 3"></ListItem>
                <ListItem title="Item 4"></ListItem>
              </List>
            </AccordionContent>
          </ListItem>
          <ListItem accordionItem title="Integer semper">
            <AccordionContent>
              <Block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque
                  nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer
                  semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est
                  rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra
                  blandit suscipit eget ipsum.
                </p>
              </Block>
            </AccordionContent>
          </ListItem>
        </List>

        <BlockTitle>Opposite Side</BlockTitle>
        <List accordionList accordionOpposite>
          <ListItem accordionItem title="Lorem Ipsum">
            <AccordionContent>
              <Block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque
                  nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer
                  semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est
                  rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra
                  blandit suscipit eget ipsum.
                </p>
              </Block>
            </AccordionContent>
          </ListItem>
          <ListItem accordionItem title="Nested List">
            <AccordionContent>
              <List>
                <ListItem title="Item 1"></ListItem>
                <ListItem title="Item 2"></ListItem>
                <ListItem title="Item 3"></ListItem>
                <ListItem title="Item 4"></ListItem>
              </List>
            </AccordionContent>
          </ListItem>
          <ListItem accordionItem title="Integer semper">
            <AccordionContent>
              <Block>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum id neque
                  nec commodo. Sed vel justo at turpis laoreet pellentesque quis sed lorem. Integer
                  semper arcu nibh, non mollis arcu tempor vel. Sed pharetra tortor vitae est
                  rhoncus, vel congue dui sollicitudin. Donec eu arcu dignissim felis viverra
                  blandit suscipit eget ipsum.
                </p>
              </Block>
            </AccordionContent>
          </ListItem>
        </List>

        <BlockTitle>Custom Collapsible</BlockTitle>
        <Block inner accordionList>
          {Array.from(Array(3).keys()).map((n) => (
            <AccordionItem key={n}>
              <AccordionToggle>
                <b>Item {n + 1}</b>
              </AccordionToggle>
              <AccordionContent>Content {n + 1}</AccordionContent>
            </AccordionItem>
          ))}
        </Block>
      </Page>
    </View>
  </App>
);
