// src/pug/docs-demos/vue/button.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Buttons"></f7-navbar>

        <f7-block-title>Usual Buttons</f7-block-title>
        <f7-block>
          <f7-row>
            <f7-col>
              <f7-button>Button</f7-button>
            </f7-col>
            <f7-col>
              <f7-button>Button</f7-button>
            </f7-col>
            <f7-col>
              <f7-button round>Round</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>

        <f7-block-title>Fill Buttons</f7-block-title>
        <f7-block>
          <f7-row>
            <f7-col>
              <f7-button fill>Button</f7-button>
            </f7-col>
            <f7-col>
              <f7-button fill>Button</f7-button>
            </f7-col>
            <f7-col>
              <f7-button fill round>Round</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>

        <f7-block-title>Outline Buttons</f7-block-title>
        <f7-block>
          <f7-row>
            <f7-col>
              <f7-button outline>Button</f7-button>
            </f7-col>
            <f7-col>
              <f7-button outline>Button</f7-button>
            </f7-col>
            <f7-col>
              <f7-button outline round>Round</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>

        <f7-block-title>Raised Buttons</f7-block-title>
        <f7-block>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button raised>Button</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button raised fill>Fill</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button raised outline>Outline</f7-button>
            </f7-col>
          </f7-row>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button raised round>Round</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button raised fill round>Fill</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button raised outline round>Outline</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>

        <f7-block-title>Segmented</f7-block-title>
        <f7-block>
          <f7-segmented raised tag="p">
            <f7-button>Button</f7-button>
            <f7-button>Button</f7-button>
            <f7-button active>Active</f7-button>
          </f7-segmented>
          <f7-segmented strong tag="p">
            <f7-button>Button</f7-button>
            <f7-button>Button</f7-button>
            <f7-button active>Active</f7-button>
          </f7-segmented>
          <f7-segmented tag="p">
            <f7-button outline>Outline</f7-button>
            <f7-button outline>Outline</f7-button>
            <f7-button outline active>Active</f7-button>
          </f7-segmented>
          <f7-segmented raised round tag="p">
            <f7-button round>Button</f7-button>
            <f7-button round>Button</f7-button>
            <f7-button round active>Active</f7-button>
          </f7-segmented>
          <f7-segmented round tag="p">
            <f7-button round outline>Outline</f7-button>
            <f7-button round outline>Outline</f7-button>
            <f7-button round outline active>Active</f7-button>
          </f7-segmented>
        </f7-block>

        <f7-block-title>Large Buttons</f7-block-title>
        <f7-block>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button large>Button</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button large fill>Fill</f7-button>
            </f7-col>
          </f7-row>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button large raised>Raised</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button large raised fill>Raised Fill</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>

        <f7-block-title>Small Buttons</f7-block-title>
        <f7-block>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button large small>Button</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button large small outline>Outline</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button large small fill>Fill</f7-button>
            </f7-col>
          </f7-row>
          <f7-row tag="p">
            <f7-col tag="span">
              <f7-button large small round>Button</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button large small outline round>Outline</f7-button>
            </f7-col>
            <f7-col tag="span">
              <f7-button large small fill round>Fill</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>

        <f7-block-title>Color Buttons</f7-block-title>
        <f7-block>
          <f7-row>
            <f7-col>
              <f7-button color="red">Red</f7-button>
            </f7-col>
            <f7-col>
              <f7-button color="green">Green</f7-button>
            </f7-col>
            <f7-col>
              <f7-button color="blue">Blue</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>

        <f7-block-title>Color Fill Buttons</f7-block-title>
        <f7-block>
          <f7-row>
            <f7-col>
              <f7-button fill color="red">Red</f7-button>
            </f7-col>
            <f7-col>
              <f7-button fill color="green">Green</f7-button>
            </f7-col>
            <f7-col>
              <f7-button fill color="blue">Blue</f7-button>
            </f7-col>
          </f7-row>
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>

// src/pug/docs-demos/react/button.jsx
import React from 'react';

export default () => (
  <App>
    <View main>
      <Page>
        <Navbar title="Buttons" />

        <BlockTitle>Usual Buttons</BlockTitle>
        <Block>
          <Row>
            <Col>
              <Button>Button</Button>
            </Col>
            <Col>
              <Button>Button</Button>
            </Col>
            <Col>
              <Button round>Round</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Fill Buttons</BlockTitle>
        <Block>
          <Row>
            <Col>
              <Button fill>Button</Button>
            </Col>
            <Col>
              <Button fill>Button</Button>
            </Col>
            <Col>
              <Button fill round>
                Round
              </Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Outline Buttons</BlockTitle>
        <Block>
          <Row>
            <Col>
              <Button outline>Button</Button>
            </Col>
            <Col>
              <Button outline>Button</Button>
            </Col>
            <Col>
              <Button outline round>
                Round
              </Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Raised Buttons</BlockTitle>
        <Block>
          <Row tag="p">
            <Col tag="span">
              <Button raised>Button</Button>
            </Col>
            <Col tag="span">
              <Button raised fill>
                Fill
              </Button>
            </Col>
            <Col tag="span">
              <Button raised outline>
                Outline
              </Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button raised round>
                Round
              </Button>
            </Col>
            <Col tag="span">
              <Button raised fill round>
                Fill
              </Button>
            </Col>
            <Col tag="span">
              <Button raised outline round>
                Outline
              </Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Segmented</BlockTitle>
        <Block>
          <Segmented raised tag="p">
            <Button>Button</Button>
            <Button>Button</Button>
            <Button active>Active</Button>
          </Segmented>
          <Segmented strong tag="p">
            <Button>Button</Button>
            <Button>Button</Button>
            <Button active>Active</Button>
          </Segmented>
          <Segmented tag="p">
            <Button outline>Outline</Button>
            <Button outline>Outline</Button>
            <Button outline active>
              Active
            </Button>
          </Segmented>
          <Segmented raised round tag="p">
            <Button round>Button</Button>
            <Button round>Button</Button>
            <Button round active>
              Active
            </Button>
          </Segmented>
          <Segmented round tag="p">
            <Button round outline>
              Outline
            </Button>
            <Button round outline>
              Outline
            </Button>
            <Button round outline active>
              Active
            </Button>
          </Segmented>
        </Block>

        <BlockTitle>Large Buttons</BlockTitle>
        <Block>
          <Row tag="p">
            <Col tag="span">
              <Button large>Button</Button>
            </Col>
            <Col tag="span">
              <Button large fill>
                Fill
              </Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button large raised>
                Raised
              </Button>
            </Col>
            <Col tag="span">
              <Button large raised fill>
                Raised Fill
              </Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Small Buttons</BlockTitle>
        <Block>
          <Row tag="p">
            <Col tag="span">
              <Button large small>
                Button
              </Button>
            </Col>
            <Col tag="span">
              <Button large small outline>
                Outline
              </Button>
            </Col>
            <Col tag="span">
              <Button large small fill>
                Fill
              </Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button large small round>
                Button
              </Button>
            </Col>
            <Col tag="span">
              <Button large small outline round>
                Outline
              </Button>
            </Col>
            <Col tag="span">
              <Button large small fill round>
                Fill
              </Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Color Buttons</BlockTitle>
        <Block>
          <Row>
            <Col>
              <Button color="red">Red</Button>
            </Col>
            <Col>
              <Button color="green">Green</Button>
            </Col>
            <Col>
              <Button color="blue">Blue</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Color Fill Buttons</BlockTitle>
        <Block>
          <Row>
            <Col>
              <Button fill color="red">
                Red
              </Button>
            </Col>
            <Col>
              <Button fill color="green">
                Green
              </Button>
            </Col>
            <Col>
              <Button fill color="blue">
                Blue
              </Button>
            </Col>
          </Row>
        </Block>
      </Page>
    </View>
  </App>
);
