// src/pug/docs-demos/svelte/infinite-scroll.svelte
<App>
  <View main>
    <Page
      infinite
      infiniteDistance={50}
      infinitePreloader={showPreloader}
      onInfinite={loadMore}
    >
      <Navbar title="Infinite Scroll"></Navbar>
      <BlockTitle>Scroll bottom</BlockTitle>
      <List>
        {#each items as item, index (index)}
          <ListItem title={`Item ${item}`}></ListItem>
        {/each}
      </List>
    </Page>
  </View>
</App>
<script>
  import {App, View, Page, Navbar, BlockTitle, List, ListItem} from 'framework7-svelte';

  let items = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
  let allowInfinite = true;
  let showPreloader = true;

  function loadMore() {
    if (!allowInfinite) return;
    allowInfinite = false;

    setTimeout(() => {
      if (items.length >= 200) {
        showPreloader = false;
        return;
      }

      const itemsLength = items.length;

      for (let i = 1; i <= 20; i += 1) {
        items.push(itemsLength + i);
      }

      items = items;
      allowInfinite = true;
    }, 1000);
  }
</script>

// src/pug/docs-demos/react/infinite-scroll.jsx
import React, { useState, useRef } from 'react';
import { App, View, Page, Navbar, BlockTitle, List, ListItem } from 'framework7-react';

export default () => {
  const allowInfinite = useRef(true);
  const [items, setItems] = useState([
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
  ]);
  const [showPreloader, setShowPreloader] = useState(true);

  const loadMore = () => {
    if (!allowInfinite.current) return;
    allowInfinite.current = false;

    setTimeout(() => {
      if (items.length >= 200) {
        setShowPreloader(false);
        return;
      }

      const itemsLength = items.length;

      for (let i = 1; i <= 20; i += 1) {
        items.push(itemsLength + i);
      }
      allowInfinite.current = true;
      setItems([...items]);
    }, 1000);
  };

  return (
    <App>
      <View main>
        <Page
          infinite
          infiniteDistance={50}
          infinitePreloader={showPreloader}
          onInfinite={loadMore}
        >
          <Navbar title="Infinite Scroll" />
          <BlockTitle>Scroll bottom</BlockTitle>
          <List>
            {items.map((item, index) => (
              <ListItem title={`Item ${item}`} key={index}></ListItem>
            ))}
          </List>
        </Page>
      </View>
    </App>
  );
};
