// src/pug/docs-demos/vue/list-button.vue
<template>
    <f7-app>
      <f7-view main>
        <f7-page>
          <f7-navbar title="List Button"></f7-navbar>
          <f7-list>
            <f7-list-button title="List Button 1"></f7-list-button>
            <f7-list-button title="List Button 2"></f7-list-button>
            <f7-list-button title="List Button 3"></f7-list-button>
          </f7-list>
          <f7-list inset>
            <f7-list-button title="List Button 1"></f7-list-button>
            <f7-list-button title="List Button 2"></f7-list-button>
            <f7-list-button title="List Button 3"></f7-list-button>
          </f7-list>
          <f7-list inset>
            <f7-list-button title="Red List Button" color="red"></f7-list-button>
            <f7-list-button title="Green List Button" color="green"></f7-list-button>
            <f7-list-button title="Orange List Button" color="orange"></f7-list-button>
          </f7-list>
        </f7-page>
      </f7-view>
    </f7-app>

</template>

// src/pug/docs-demos/react/list-button.jsx
import React from 'react';

export default () => (
  <App>
    <View main>
      <Page>
        <Navbar title="List Button" />
        <List>
          <ListButton title="List Button 1" />
          <ListButton title="List Button 2" />
          <ListButton title="List Button 3" />
        </List>

        <List inset>
          <ListButton title="List Button 1" />
          <ListButton title="List Button 2" />
          <ListButton title="List Button 3" />
        </List>

        <List inset>
          <ListButton title="Red List Button" color="red" />
          <ListButton title="Green List Button" color="green" />
          <ListButton title="Orange List Button" color="orange" />
        </List>
      </Page>
    </View>
  </App>
);
