// src/pug/docs-demos/vue/store_page.vue
<template>
  <f7-page>
    <f7-navbar title="Store" />
    <f7-list v-if="users.length">
      <f7-list-item v-for="user in users" :title="user" />
    </f7-list>
    <f7-block v-else strong>
      <f7-button fill preloader :loading="loading" @click="loadUsers"> Load Users </f7-button>
    </f7-block>
  </f7-page>
</template>
<script>
import { useStore } from 'framework7-vue';
import store from './store';

export default {
  setup() {
    const loading = useStore('loading');
    const users = useStore('users');

    const loadUsers = () => {
      store.dispatch('getUsers');
    };

    return {
      loading,
      users,
      loadUsers,
    };
  },
};
</script>

// src/pug/docs-demos/react/store_page.jsx
import React from 'react';
import { useStore, Page, Navbar, Block, List, ListItem, Button } from 'framework7-react';
import store from './store';

export default () => {
  const loading = useStore('loading');
  const users = useStore('users');

  const loadUsers = () => {
    store.dispatch('getUsers');
  };

  return (
    <Page>
      <Navbar title="Store" />
      {users.length && (
        <List>
          {users.map((user) => (
            <ListItem title={user} key={user} />
          ))}
        </List>
      )}
      {!users.length && (
        <Block strong>
          <Button fill preloader loading={loading} onClick={loadUsers}>
            Load Users
          </Button>
        </Block>
      )}
    </Page>
  );
};
