// src/pug/docs-demos/svelte/store_page.svelte
<Page>
  <Navbar title="Store" />
  {#if users.length}
    <List>
      {#each users as user}
        <ListItem title={user} />
      {/each}
    </List>
  {:else}
    <Block strong>
      <Button fill preloader loading={loading} onClick={loadUsers}>
        Load Users
      </Button>
    </Block>
  {/if}
</Page>
<script>
import { useStore, Page, Navbar, Block, List, ListItem, Button } from 'framework7-svelte';
import store from './store';

let loading = useStore('loading', (value) => loading = value);
let users = useStore('users', (value) => users = value);

const loadUsers = () => {
  store.dispatch('getUsers');
};
</script>

// src/pug/docs-demos/react/store_page.jsx
import React from 'react';
import { useStore, Page, Navbar, Block, List, ListItem, Button } from 'framework7-react';
import store from './store';

export default () => {
  const loading = useStore('loading');
  const users = useStore('users');

  const loadUsers = () => {
    store.dispatch('getUsers');
  };

  return (
    <Page>
      <Navbar title="Store" />
      {users.length && (
        <List>
          {users.map((user) => (
            <ListItem title={user} key={user} />
          ))}
        </List>
      )}
      {!users.length && (
        <Block strong>
          <Button fill preloader loading={loading} onClick={loadUsers}>
            Load Users
          </Button>
        </Block>
      )}
    </Page>
  );
};
