// src/pug/docs-demos/vue/tabs.vue
<template>
  <f7-app :routes="routes">
    <f7-view main>
      <f7-page>
        <f7-navbar title="Tabs"></f7-navbar>
        <f7-list>
          <f7-list-item link="/tabs-static/" title="Static Tabs"></f7-list-item>
          <f7-list-item link="/tabs-animated/" title="Animated Tabs"></f7-list-item>
          <f7-list-item link="/tabs-swipeable/" title="Swipeable Tabs"></f7-list-item>
        </f7-list>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
<script>
import TabsStatic from './tabs_static.vue';
import TabsAnimated from './tabs_animated.vue';
import TabsSwipeable from './tabs_swipeable.vue';

export default {
  data() {
    return {
      routes: [
        {
          path: '/tabs-static/',
          component: TabsStatic,
        },
        {
          path: '/tabs-animated/',
          component: TabsAnimated,
        },
        {
          path: '/tabs-swipeable/',
          component: TabsSwipeable,
        },
      ],
    };
  },
};
</script>

// src/pug/docs-demos/react/tabs.jsx
import React from 'react';
import { Page, Navbar, App, View, List, ListItem } from 'framework7-react';

import TabsStatic from './tabs_static.jsx';
import TabsAnimated from './tabs_animated.jsx';
import TabsSwipeable from './tabs_swipeable.jsx';

const routes = [
  {
    path: '/tabs-static/',
    component: TabsStatic,
  },
  {
    path: '/tabs-animated/',
    component: TabsAnimated,
  },
  {
    path: '/tabs-swipeable/',
    component: TabsSwipeable,
  },
];

export default () => (
  <App routes={routes}>
    <View main>
      <Page>
        <Navbar title="Tabs" />
        <List>
          <ListItem link="/tabs-static/" title="Static Tabs" />
          <ListItem link="/tabs-animated/" title="Animated Tabs" />
          <ListItem link="/tabs-swipeable/" title="Swipeable Tabs" />
        </List>
      </Page>
    </View>
  </App>
);
