// src/pug/docs-demos/svelte/action-sheet.svelte
<App>
  <View main>
    <Page>
      <Navbar title="Action Sheet" />
      <Block strong>
        <p class="row">
          <!-- One group, open by "actionsOpen" attribute -->
          <Button class="col" raised actionsOpen="#actions-one-group">One group</Button>
          <!--  Two groups, open by "actionsOpen" attribute -->
          <Button class="col" raised actionsOpen="#actions-two-groups">Two groups</Button>
        </p>
        <p>
          <!-- Actions Grid, open by changing actionGridOpened state property -->
          <Button raised onClick={() => actionGridOpened = true}>Action Grid</Button>
        </p>
      </Block>

      <BlockTitle>Action Sheet To Popover</BlockTitle>
      <Block strong>
        <p bind:this={buttonToPopoverWrapper}>
          Action Sheet can be automatically converted to Popover (for tablets). This button will open Popover on tablets and Action Sheet on phones:
          <Button
            style="display: inline-block"
            class="button-to-popover"
            onClick={openActionsPopover}
          >
            Actions
          </Button>
        </p>
      </Block>

      <!-- One Group -->
      <Actions id="actions-one-group">
        <ActionsGroup>
          <ActionsLabel>Do something</ActionsLabel>
          <ActionsButton bold>Button 1</ActionsButton>
          <ActionsButton>Button 2</ActionsButton>
          <ActionsButton color="red">Cancel</ActionsButton>
        </ActionsGroup>
      </Actions>

      <!-- Two Groups -->
      <Actions id="actions-two-groups">
        <ActionsGroup>
          <ActionsLabel>Do something</ActionsLabel>
          <ActionsButton bold>Button 1</ActionsButton>
          <ActionsButton>Button 2</ActionsButton>
        </ActionsGroup>
        <ActionsGroup>
          <ActionsButton color="red">Cancel</ActionsButton>
        </ActionsGroup>
      </Actions>

      <!-- Grid -->
      <Actions grid={true} opened={actionGridOpened} onActionsClosed={() => actionGridOpened = false}>
        <ActionsGroup>
          <ActionsButton>
            <img slot="media" src="https://cdn.framework7.io/placeholder/people-96x96-1.jpg" width="48"/>
            <span>Button 1</span>
          </ActionsButton>
          <ActionsButton>
            <img slot="media" src="https://cdn.framework7.io/placeholder/people-96x96-2.jpg" width="48"/>
            <span>Button 2</span>
          </ActionsButton>
          <ActionsButton>
            <img slot="media" src="https://cdn.framework7.io/placeholder/people-96x96-3.jpg" width="48"/>
            <span>Button 3</span>
          </ActionsButton>
        </ActionsGroup>
        <ActionsGroup>
          <ActionsButton>
            <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-96x96-4.jpg" width="48"/>
            <span>Button 4</span>
          </ActionsButton>
          <ActionsButton>
            <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-96x96-5.jpg" width="48"/>
            <span>Button 5</span>
          </ActionsButton>
          <ActionsButton>
            <img slot="media" src="https://cdn.framework7.io/placeholder/fashion-96x96-6.jpg" width="48"/>
            <span>Button 6</span>
          </ActionsButton>
        </ActionsGroup>
      </Actions>
    </Page>
  </View>
</App>
<script>
  import { onDestroy } from 'svelte';
  import { f7, App, View, Page, Navbar, Block, BlockTitle, Button, Actions, ActionsGroup, ActionsLabel, ActionsButton } from 'framework7-svelte';

  let actionGridOpened = false;
  let actionsToPopover = null;
  let buttonToPopoverWrapper;

  onDestroy(() => {
    if (actionsToPopover) {
      actionsToPopover.destroy();
    }
  })

  function openActionsPopover() {
    if (!actionsToPopover) {
      actionsToPopover = f7.actions.create({
        buttons: [
          {
            text: 'Do something',
            label: true,
          },
          {
            text: 'Button 1',
            bold: true,
          },
          {
            text: 'Button 2',
          },
          {
            text: 'Cancel',
            color: 'red',
          },
        ],
        // Need to specify popover target
        targetEl: buttonToPopoverWrapper.querySelector('.button-to-popover'),
      });
    }

    // Open
    actionsToPopover.open();
  }

</script>

// src/pug/docs-demos/vue/action-sheet.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Action Sheet"></f7-navbar>
        <f7-block strong>
          <p class="row">
            <!-- One group, open by "actions-open" attribute -->
            <f7-button class="col" raised actions-open="#actions-one-group">One group</f7-button>
            <!-- Two groups, open by "actions-open" attribute -->
            <f7-button class="col" raised actions-open="#actions-two-groups">Two groups</f7-button>
          </p>
          <p>
            <!-- Actions Grid, open by changing actionGridOpened prop -->
            <f7-button raised @click="actionGridOpened = true">Action Grid</f7-button>
          </p>
        </f7-block>

        <f7-block-title>Action Sheet To Popover</f7-block-title>
        <f7-block strong>
          <p>Action Sheet can be automatically converted to Popover (for tablets). This button will open Popover on tablets and Action Sheet on phones: <f7-button style="display:inline-block" class="button-to-popover" @click="openActionsPopover">Actions</f7-button></p>
        </f7-block>

        <!-- One Group -->
        <f7-actions id="actions-one-group">
          <f7-actions-group>
            <f7-actions-label>Do something</f7-actions-label>
            <f7-actions-button bold>Button 1</f7-actions-button>
            <f7-actions-button>Button 2</f7-actions-button>
            <f7-actions-button color="red">Cancel</f7-actions-button>
          </f7-actions-group>
        </f7-actions>

        <!-- Two Groups -->
        <f7-actions id="actions-two-groups">
          <f7-actions-group>
            <f7-actions-label>Do something</f7-actions-label>
            <f7-actions-button bold>Button 1</f7-actions-button>
            <f7-actions-button>Button 2</f7-actions-button>
          </f7-actions-group>
          <f7-actions-group>
            <f7-actions-button color="red">Cancel</f7-actions-button>
          </f7-actions-group>
        </f7-actions>

        <!-- Grid -->
        <f7-actions :grid="true" :opened="actionGridOpened" @actions:closed="actionGridOpened = false">
          <f7-actions-group>
            <f7-actions-button>
              <template #media>
                <img src="https://cdn.framework7.io/placeholder/people-96x96-1.jpg" width="48"/>
              </template>
              <span>Button 1</span>
            </f7-actions-button>
            <f7-actions-button>
              <template #media>
                <img src="https://cdn.framework7.io/placeholder/people-96x96-2.jpg" width="48"/>
              </template>
              <span>Button 2</span>
            </f7-actions-button>
            <f7-actions-button>
              <template #media>
                <img src="https://cdn.framework7.io/placeholder/people-96x96-3.jpg" width="48"/>
              </template>
              <span>Button 3</span>
            </f7-actions-button>
          </f7-actions-group>
          <f7-actions-group>
            <f7-actions-button>
              <template #media>
                <img src="https://cdn.framework7.io/placeholder/fashion-96x96-4.jpg" width="48"/>
              </template>
              <span>Button 4</span>
            </f7-actions-button>
            <f7-actions-button>
              <template #media>
                <img src="https://cdn.framework7.io/placeholder/fashion-96x96-5.jpg" width="48"/>
              </template>
              <span>Button 5</span>
            </f7-actions-button>
            <f7-actions-button>
              <template #media>
                <img src="https://cdn.framework7.io/placeholder/fashion-96x96-6.jpg" width="48"/>
              </template>
              <span>Button 6</span>
            </f7-actions-button>
          </f7-actions-group>
        </f7-actions>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
<script>
  import { f7 } from 'framework7-vue';

  export default {
    data() {
      return {
        actionGridOpened: false,
      };
    },
    methods: {
      openActionsPopover() {
        const self = this;
        if (!self.actionsToPopover) {
          self.actionsToPopover = f7.actions.create({
            buttons: [
              {
                text: 'Do something',
                label: true,
              },
              {
                text: 'Button 1',
                bold: true,
              },
              {
                text: 'Button 2',
              },
              {
                text: 'Cancel',
                color: 'red',
              },
            ],
            // Need to specify popover target
            targetEl: self.$el.querySelector('.button-to-popover'),
          });
        }

        // Open
        self.actionsToPopover.open();
      },
    },
  }
</script>
