// src/pug/docs-demos/react/area-chart.jsx
import React from 'react';
import { App, View, Page, Navbar, BlockTitle, Block, AreaChart } from 'framework7-react';

export default () => {
  // helpers data for axis
  const dates = [];
  const today = new Date();
  const year = today.getFullYear();
  const month = today.getMonth();
  for (let i = 0; i < 4; i += 1) {
    dates.push(new Date(year, month - (3 - i)));
  }
  const axisDateFormat = Intl.DateTimeFormat(undefined, { month: 'short', year: 'numeric' });
  const tooltipDateFormat = Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' });

  return (
    <App>
      <View main>
        <Page>
          <Navbar title="Area Chart" />
          <BlockTitle>Simple Area Chart</BlockTitle>
          <Block strong>
            <AreaChart
              datasets={[
                {
                  color: '#f00',
                  values: [0, 100, 250, 300, 175, 400],
                },
                {
                  color: '#00f',
                  values: [100, 75, 133, 237, 40, 200],
                },
                {
                  color: '#ff0',
                  values: [100, 300, 127, 40, 250, 80],
                },
              ]}
            />
          </Block>
          <BlockTitle>Area Chart With Tooltip</BlockTitle>
          <Block strong>
            <AreaChart
              tooltip
              datasets={[
                {
                  label: 'Red data',
                  color: '#f00',
                  values: [100, 75, 133, 237, 40, 200],
                },
                {
                  label: 'Blue data',
                  color: '#00f',
                  values: [100, 300, 127, 40, 250, 80],
                },
                {
                  label: 'Yellow data',
                  color: '#ff0',
                  values: [0, 100, 250, 300, 175, 400],
                },
              ]}
            />
          </Block>
          <BlockTitle>Area Chart With Axis</BlockTitle>
          <Block strong>
            <AreaChart
              tooltip
              axis
              axisLabels={dates}
              formatAxisLabel={(date) => axisDateFormat.format(date)}
              formatTooltipAxisLabel={(date) => tooltipDateFormat.format(date)}
              datasets={[
                {
                  label: 'Green data',
                  color: '#0f0',
                  values: [100, 75, 133, 237],
                },
                {
                  label: 'Red data',
                  color: '#f00',
                  values: [100, 300, 127, 47],
                },
                {
                  label: 'Yellow data',
                  color: '#ff0',
                  values: [0, 100, 250, 307],
                },
              ]}
            />
          </Block>
          <BlockTitle>Area Chart With Legend</BlockTitle>
          <Block strong>
            <AreaChart
              tooltip
              axis
              axisLabels={dates}
              legend
              toggleDatasets
              formatAxisLabel={(date) => axisDateFormat.format(date)}
              formatTooltipAxisLabel={(date) => tooltipDateFormat.format(date)}
              datasets={[
                {
                  label: 'Red data',
                  color: '#f00',
                  values: [100, 300, 127, 47],
                },
                {
                  label: 'Blue data',
                  color: '#00f',
                  values: [100, 75, 133, 237],
                },
                {
                  label: 'Yellow data',
                  color: '#ff0',
                  values: [0, 100, 250, 307],
                },
              ]}
            />
          </Block>
          <BlockTitle>Lines Chart</BlockTitle>
          <Block strong>
            <AreaChart
              tooltip
              axis
              axisLabels={dates}
              legend
              toggleDatasets
              lineChart
              formatAxisLabel={(date) => axisDateFormat.format(date)}
              formatTooltipAxisLabel={(date) => tooltipDateFormat.format(date)}
              datasets={[
                {
                  label: 'Red data',
                  color: '#f00',
                  values: [0, 300, 127, 47],
                },
                {
                  label: 'Blue data',
                  color: '#00f',
                  values: [0, 75, 133, 237],
                },
                {
                  label: 'Green data',
                  color: '#0f0',
                  values: [0, 100, 250, 307],
                },
              ]}
            />
          </Block>
        </Page>
      </View>
    </App>
  );
};

// src/pug/docs-demos/vue/area-chart.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Area Chart" />

        <f7-block-title>Simple Area Chart</f7-block-title>
        <f7-block strong>
          <f7-area-chart
            :datasets="[
              {
                color: '#f00',
                values: [0, 100, 250, 300, 175, 400],
              },
              {
                color: '#00f',
                values: [100, 75, 133, 237, 40, 200],
              },
              {
                color: '#ff0',
                values: [100, 300, 127, 40, 250, 80],
              },
            ]"
          />
        </f7-block>
        <f7-block-title>Area Chart With Tooltip</f7-block-title>
        <f7-block strong>
          <f7-area-chart
            tooltip
            :datasets="[
              {
                label: 'Red data',
                color: '#f00',
                values: [100, 75, 133, 237, 40, 200],
              },
              {
                label: 'Blue data',
                color: '#00f',
                values: [100, 300, 127, 40, 250, 80],
              },
              {
                label: 'Yellow data',
                color: '#ff0',
                values: [0, 100, 250, 300, 175, 400],
              },
            ]"
          />
        </f7-block>
        <f7-block-title>Area Chart With Axis</f7-block-title>
        <f7-block strong>
          <f7-area-chart
            tooltip
            axis
            :axis-labels="dates"
            :format-axis-label="(date) => axisDateFormat.format(date)"
            :format-tooltip-axis-label="(date) => tooltipDateFormat.format(date)"
            :datasets="[
              {
                label: 'Green data',
                color: '#0f0',
                values: [100, 75, 133, 237],
              },
              {
                label: 'Red data',
                color: '#f00',
                values: [100, 300, 127, 47],
              },
              {
                label: 'Yellow data',
                color: '#ff0',
                values: [0, 100, 250, 307],
              },
            ]"
          />
        </f7-block>
        <f7-block-title>Area Chart With Legend</f7-block-title>
        <f7-block strong>
          <f7-area-chart
            tooltip
            axis
            :axis-labels="dates"
            legend
            toggle-datasets
            :format-axis-label="(date) => axisDateFormat.format(date)"
            :format-tooltip-axis-label="(date) => tooltipDateFormat.format(date)"
            :datasets="[
              {
                label: 'Red data',
                color: '#f00',
                values: [100, 300, 127, 47],
              },
              {
                label: 'Blue data',
                color: '#00f',
                values: [100, 75, 133, 237],
              },
              {
                label: 'Yellow data',
                color: '#ff0',
                values: [0, 100, 250, 307],
              },
            ]"
          />
        </f7-block>
        <f7-block-title>Lines Chart</f7-block-title>
        <f7-block strong>
          <f7-area-chart
            tooltip
            axis
            :axis-labels="dates"
            legend
            toggle-datasets
            line-chart
            :format-axis-label="(date) => axisDateFormat.format(date)"
            :format-tooltip-axis-label="(date) => tooltipDateFormat.format(date)"
            :datasets="[
              {
                label: 'Red data',
                color: '#f00',
                values: [0, 300, 127, 47],
              },
              {
                label: 'Blue data',
                color: '#00f',
                values: [0, 75, 133, 237],
              },
              {
                label: 'Green data',
                color: '#0f0',
                values: [0, 100, 250, 307],
              },
            ]"
          />
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
<script>
export default {
  setup() {
    // helpers data for axis
    const dates = [];
    const today = new Date();
    const year = today.getFullYear();
    const month = today.getMonth();
    for (let i = 0; i < 4; i += 1) {
      dates.push(new Date(year, month - (3 - i)));
    }
    const axisDateFormat = Intl.DateTimeFormat(undefined, { month: 'short', year: 'numeric' });
    const tooltipDateFormat = Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' });
    return {
      dates,
      axisDateFormat,
      tooltipDateFormat,
    };
  },
};
</script>
