// src/pug/docs-demos/react/breadcrumbs.jsx
import React from 'react';
import {
  App,
  View,
  Page,
  Navbar,
  List,
  ListItem,
  Block,
  BlockTitle,
  BlockHeader,
  Link,
  Popover,
  Breadcrumbs,
  BreadcrumbsItem,
  BreadcrumbsSeparator,
  BreadcrumbsCollapsed,
} from 'framework7-react';

export default () => (
  <App>
    <View main>
      <Page>
        <Navbar title="Breadcrumbs" />
        <BlockTitle>Basic</BlockTitle>
        <Block strong>
          <Breadcrumbs>
            <BreadcrumbsItem>
              <Link>Home</Link>
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem>
              <Link>Catalog</Link>
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem active>Phones</BreadcrumbsItem>
          </Breadcrumbs>
        </Block>

        <BlockTitle>Scrollable</BlockTitle>
        <BlockHeader>Breadcrumbs will be scrollable if they don't fit the screen</BlockHeader>
        <Block strong>
          <Breadcrumbs>
            <BreadcrumbsItem>
              <Link>Home</Link>
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem>
              <Link>Catalog</Link>
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem>
              <Link>Phones</Link>
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem>
              <Link>Apple</Link>
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem active>iPhone 12</BreadcrumbsItem>
          </Breadcrumbs>
        </Block>

        <BlockTitle>Collapsed</BlockTitle>
        <Block strong>
          <Breadcrumbs>
            <BreadcrumbsItem>
              <Link>Home</Link>
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsCollapsed className="popover-open" data-popover=".breadcrumbs-popover">
              <Popover className="breadcrumbs-popover" style={{ width: '120px' }}>
                <List>
                  <ListItem link title="Catalog" popoverClose />
                  <ListItem link title="Phones" popoverClose />
                  <ListItem link title="Apple" popoverClose />
                </List>
              </Popover>
            </BreadcrumbsCollapsed>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem active>iPhone 12</BreadcrumbsItem>
          </Breadcrumbs>
        </Block>

        <BlockTitle>With Icons</BlockTitle>
        <Block strong>
          <Breadcrumbs>
            <BreadcrumbsItem>
              <Link iconIos="f7:house_fill" iconMd="material:home" text="Home" />
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem>
              <Link iconIos="f7:square_list_fill" iconMd="material:list_alt" text="Catalog" />
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem>
              <Link iconIos="f7:device_phone_portrait" iconMd="material:smartphone" text="Phones" />
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem>
              <Link iconF7="logo_apple" text="Apple" />
            </BreadcrumbsItem>
            <BreadcrumbsSeparator />
            <BreadcrumbsItem active>iPhone 12</BreadcrumbsItem>
          </Breadcrumbs>
        </Block>
      </Page>
    </View>
  </App>
);

// src/pug/docs-demos/vue/breadcrumbs.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Breadcrumbs"></f7-navbar>

        <f7-block-title>Basic</f7-block-title>
        <f7-block strong>
          <f7-breadcrumbs>
            <f7-breadcrumbs-item>
              <f7-link>Home</f7-link>
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item>
              <f7-link>Catalog</f7-link>
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item active>Phones</f7-breadcrumbs-item>
          </f7-breadcrumbs>
        </f7-block>

        <f7-block-title>Scrollable</f7-block-title>
        <f7-block-header
          >Breadcrumbs will be scrollable if they don't fit the screen</f7-block-header
        >
        <f7-block strong>
          <f7-breadcrumbs>
            <f7-breadcrumbs-item>
              <f7-link>Home</f7-link>
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item>
              <f7-link>Catalog</f7-link>
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item>
              <f7-link>Phones</f7-link>
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item>
              <f7-link>Apple</f7-link>
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item active>iPhone 12</f7-breadcrumbs-item>
          </f7-breadcrumbs>
        </f7-block>

        <f7-block-title>Collapsed</f7-block-title>
        <f7-block strong>
          <f7-breadcrumbs>
            <f7-breadcrumbs-item>
              <f7-link>Home</f7-link>
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-collapsed class="popover-open" data-popover=".breadcrumbs-popover">
              <f7-popover class="breadcrumbs-popover" style="width: 120px">
                <f7-list>
                  <f7-list-item link title="Catalog" popover-close />
                  <f7-list-item link title="Phones" popover-close />
                  <f7-list-item link title="Apple" popover-close />
                </f7-list>
              </f7-popover>
            </f7-breadcrumbs-collapsed>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item active>iPhone 12</f7-breadcrumbs-item>
          </f7-breadcrumbs>
        </f7-block>

        <f7-block-title>With Icons</f7-block-title>
        <f7-block strong>
          <f7-breadcrumbs>
            <f7-breadcrumbs-item>
              <f7-link icon-ios="f7:house_fill" icon-md="material:home" text="Home" />
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item>
              <f7-link icon-ios="f7:square_list_fill" icon-md="material:list_alt" text="Catalog" />
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item>
              <f7-link
                icon-ios="f7:device_phone_portrait"
                icon-md="material:smartphone"
                text="Phones"
              />
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item>
              <f7-link icon-f7="logo_apple" text="Apple" />
            </f7-breadcrumbs-item>
            <f7-breadcrumbs-separator />
            <f7-breadcrumbs-item active>iPhone 12</f7-breadcrumbs-item>
          </f7-breadcrumbs>
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
