// src/pug/docs-demos/react/chips.jsx
import React from 'react';
import { App, View, Page, Navbar, BlockTitle, Block, Chip, Icon, f7 } from 'framework7-react';

export default () => {
  const deleteChip = (e) => {
    const target = e.target;
    f7.dialog.confirm('Do you want to delete this tiny demo Chip?', () => {
      f7.$(target).parents('.chip').remove();
    });
  };

  return (
    <App>
      <View main>
        <Page>
          <Navbar title="Chips" />
          <BlockTitle>Chips With Text</BlockTitle>
          <Block strong>
            <Chip text="Example Chip" />
            <Chip text="Another Chip" />
            <Chip text="One More Chip" />
            <Chip text="Fourth Chip" />
            <Chip text="Last One" />
          </Block>
          <BlockTitle>Outline Chips</BlockTitle>
          <Block strong>
            <Chip outline text="Example Chip" />
            <Chip outline text="Another Chip" />
            <Chip outline text="One More Chip" />
            <Chip outline text="Fourth Chip" />
            <Chip outline text="Last One" />
          </Block>
          <BlockTitle>Icon Chips</BlockTitle>
          <Block strong>
            <Chip text="Add Contact" mediaBgColor="blue">
              <Icon
                slot="media"
                ios="f7:plus_circle"
                aurora="f7:plus_circle"
                md="material:add_circle"
              />
            </Chip>
            <Chip text="London" mediaBgColor="green">
              <Icon slot="media" ios="f7:compass" aurora="f7:compass" md="material:location_on" />
            </Chip>
            <Chip text="John Doe" mediaBgColor="red">
              <Icon slot="media" ios="f7:person" aurora="f7:person" md="material:person" />
            </Chip>
          </Block>
          <BlockTitle>Contact Chips</BlockTitle>
          <Block strong>
            <Chip text="Jane Doe">
              <img slot="media" src="https://cdn.framework7.io/placeholder/people-100x100-9.jpg" />
            </Chip>
            <Chip text="John Doe">
              <img slot="media" src="https://cdn.framework7.io/placeholder/people-100x100-3.jpg" />
            </Chip>
            <Chip text="Adam Smith">
              <img slot="media" src="https://cdn.framework7.io/placeholder/people-100x100-7.jpg" />
            </Chip>
            <Chip text="Jennifer" mediaBgColor="pink" media="J" />
            <Chip text="Chris" mediaBgColor="yellow" mediaTextColor="black" media="C" />
            <Chip text="Kate" mediaBgColor="red" media="K" />
          </Block>
          <BlockTitle>Deletable Chips / Tags</BlockTitle>
          <Block strong>
            <Chip text="Example Chip" deleteable onDelete={deleteChip} />
            <Chip
              text="Chris"
              media="C"
              mediaBgColor="orange"
              textColor="black"
              deleteable
              onDelete={deleteChip}
            />
            <Chip text="Jane Doe" deleteable onDelete={deleteChip}>
              <img slot="media" src="https://cdn.framework7.io/placeholder/people-100x100-9.jpg" />
            </Chip>
            <Chip text="One More Chip" deleteable onDelete={deleteChip} />
            <Chip text="Jennifer" mediaBgColor="pink" media="J" deleteable onDelete={deleteChip} />
            <Chip text="Adam Smith" deleteable onDelete={deleteChip}>
              <img slot="media" src="https://cdn.framework7.io/placeholder/people-100x100-7.jpg" />
            </Chip>
          </Block>
          <BlockTitle>Color Chips</BlockTitle>
          <Block strong>
            <Chip text="Red Chip" color="red" />
            <Chip text="Green Chip" color="green" />
            <Chip text="Blue Chip" color="blue" />
            <Chip text="Orange Chip" color="orange" />
            <Chip text="Pink Chip" color="pink" />
            <Chip outline text="Red Chip" color="red" />
            <Chip outline text="Green Chip" color="green" />
            <Chip outline text="Blue Chip" color="blue" />
            <Chip outline text="Orange Chip" color="orange" />
            <Chip outline text="Pink Chip" color="pink" />
          </Block>
        </Page>
      </View>
    </App>
  );
};

// src/pug/docs-demos/vue/chips.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Chips"></f7-navbar>

        <f7-block-title>Chips With Text</f7-block-title>
        <f7-block strong>
          <f7-chip text="Example Chip"></f7-chip>
          <f7-chip text="Another Chip"></f7-chip>
          <f7-chip text="One More Chip"></f7-chip>
          <f7-chip text="Fourth Chip"></f7-chip>
          <f7-chip text="Last One"></f7-chip>
        </f7-block>

        <f7-block-title>Outline Chips</f7-block-title>
        <f7-block strong>
          <f7-chip outline text="Example Chip"></f7-chip>
          <f7-chip outline text="Another Chip"></f7-chip>
          <f7-chip outline text="One More Chip"></f7-chip>
          <f7-chip outline text="Fourth Chip"></f7-chip>
          <f7-chip outline text="Last One"></f7-chip>
        </f7-block>

        <f7-block-title>Icon Chips</f7-block-title>
        <f7-block strong>
          <f7-chip text="Add Contact" media-bg-color="blue">
            <template #media>
              <f7-icon ios="f7:plus_circle" aurora="f7:plus_circle" md="material:add_circle"></f7-icon>
            </template>
          </f7-chip>
          <f7-chip text="London" media-bg-color="green">
            <template #media>
              <f7-icon ios="f7:compass" aurora="f7:compass" md="material:location_on"></f7-icon>
            </template>
          </f7-chip>
          <f7-chip text="John Doe" media-bg-color="red">
            <template #media>
              <f7-icon ios="f7:person" aurora="f7:person" md="material:person"></f7-icon>
            </template>
          </f7-chip>
        </f7-block>

        <f7-block-title>Contact Chips</f7-block-title>
        <f7-block strong>
          <f7-chip text="Jane Doe">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-100x100-9.jpg"/>
            </template>
          </f7-chip>
          <f7-chip text="John Doe">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-100x100-3.jpg"/>
            </template>
          </f7-chip>
          <f7-chip text="Adam Smith">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-100x100-7.jpg"/>
            </template>
          </f7-chip>
          <f7-chip text="Jennifer" media-bg-color="pink" media="J"></f7-chip>
          <f7-chip text="Chris" media-bg-color="yellow" media-text-color="black" media="C"></f7-chip>
          <f7-chip text="Kate" media-bg-color="red" media="K"></f7-chip>
        </f7-block>

        <f7-block-title>Deletable Chips / Tags</f7-block-title>
        <f7-block strong>
          <f7-chip text="Example Chip" deleteable @click="deleteChip"></f7-chip>
          <f7-chip text="Chris" media="C" media-bg-color="orange" text-color="black" deleteable @click="deleteChip"></f7-chip>
          <f7-chip text="Jane Doe" deleteable @click="deleteChip">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-100x100-9.jpg"/>
            </template>
          </f7-chip>
          <f7-chip text="One More Chip" deleteable @click="deleteChip"></f7-chip>
          <f7-chip text="Jennifer" media-bg-color="pink" media="J" deleteable @click="deleteChip"></f7-chip>
          <f7-chip text="Adam Smith" deleteable @click="deleteChip">
            <template #media>
              <img src="https://cdn.framework7.io/placeholder/people-100x100-7.jpg"/>
            </template>
          </f7-chip>
        </f7-block>

        <f7-block-title>Color Chips</f7-block-title>
        <f7-block strong>
          <f7-chip text="Red Chip" color="red"></f7-chip>
          <f7-chip text="Green Chip" color="green"></f7-chip>
          <f7-chip text="Blue Chip" color="blue"></f7-chip>
          <f7-chip text="Orange Chip" color="orange"></f7-chip>
          <f7-chip text="Pink Chip" color="pink"></f7-chip>
          <f7-chip outline text="Red Chip" color="red"></f7-chip>
          <f7-chip outline text="Green Chip" color="green"></f7-chip>
          <f7-chip outline text="Blue Chip" color="blue"></f7-chip>
          <f7-chip outline text="Orange Chip" color="orange"></f7-chip>
          <f7-chip outline text="Pink Chip" color="pink"></f7-chip>
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>

<script>
import { f7 } from 'framework7-vue';

export default {
  methods: {
    deleteChip(e) {
      const target = e.target;
      f7.dialog.confirm('Do you want to delete this tiny demo Chip?', () => {
        f7.$(target).parents('.chip').remove();
      });
    },
  },
}
</script>
