// src/pug/docs-demos/svelte/login-screen.svelte
<App routes={routes}>
  <View main url="/" />
</App>

<script>
  import {f7, App, View} from 'framework7-svelte';

  import LoginScreenMain from './login-screen_main.svelte';
  import LoginScreenPage from './login-screen_page.svelte';

  const routes = [
    {
      path: '/',
      component: LoginScreenMain,
    },
    {
      path: '/login-screen-page/',
      component: LoginScreenPage,
    },
  ];
</script>

// src/pug/docs-demos/vue/login-screen.vue
<template>
  <f7-app :routes="routes">
    <f7-view main url="/" />
  </f7-app>
</template>
<script>
  import LoginScreenMain from './login-screen_main.vue';
  import LoginScreenPage from './login-screen_page.vue';

  export default {
    data() {
      return {
        routes: [
          {
            path: '/',
            component: LoginScreenMain,
          },
          {
            path: '/login-screen-page/',
            component: LoginScreenPage,
          },
        ],
      };
    },
  }
</script>
