// src/pug/docs-demos/react/popover.jsx
import React from 'react';

export default () => (
  <App>
    <View main>
      <Page>
        <Navbar title="Popover"></Navbar>
        <Toolbar bottom>
          <Link>Dummy Link</Link>
          <Link popoverOpen=".popover-menu">Open Popover</Link>
        </Toolbar>

        <Block>
          <p>
            <Button fill raised popoverOpen=".popover-menu">
              Open popover on me
            </Button>
          </p>
          <p>
            Mauris fermentum neque et luctus venenatis. Vivamus a sem rhoncus, ornare tellus eu,
            euismod mauris. In porta turpis at semper convallis. Duis adipiscing leo eu nulla
            lacinia, quis rhoncus metus condimentum. Etiam nec malesuada nibh. Maecenas quis lacinia
            nisl, vel posuere dolor. Vestibulum condimentum, nisl ac vulputate egestas, neque enim
            dignissim elit, rhoncus volutpat magna enim a est. Aenean sit amet ligula neque. Cras
            suscipit rutrum enim. Nam a odio facilisis, elementum tellus non,{' '}
            <Link popoverOpen=".popover-menu">popover</Link> tortor. Pellentesque felis eros, dictum
            vitae lacinia quis, lobortis vitae ipsum. Cras vehicula bibendum lorem quis imperdiet.
          </p>
          <p>
            In hac habitasse platea dictumst. Etiam varius, ante vel ornare facilisis, velit massa
            rutrum dolor, ac porta magna magna lacinia nunc. Curabitur{' '}
            <Link popoverOpen=".popover-menu">popover!</Link> cursus laoreet. Aenean vel tempus
            augue. Pellentesque in imperdiet nibh. Mauris rhoncus nulla id sem suscipit volutpat.
            Pellentesque ac arcu in nisi viverra pulvinar. Nullam nulla orci, bibendum sed ligula
            non, ullamcorper iaculis mi. In hac habitasse platea dictumst. Praesent varius at nisl
            eu luctus. Cras aliquet porta est. Quisque elementum quis dui et consectetur. Cum sociis
            natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sed
            laoreet purus. Pellentesque eget ante ante.
          </p>
          <p>
            Duis et ultricies nibh. Sed facilisis turpis urna, ac imperdiet erat venenatis eu. Proin
            sit amet faucibus tortor, et varius sem. Etiam vitae lacinia neque. Aliquam nisi purus,
            interdum in arcu sed, ultrices rutrum arcu. Nulla mi turpis, consectetur vel enim quis,
            facilisis viverra dui. Aliquam quis convallis tortor, quis semper ligula. Morbi
            ullamcorper <Link popoverOpen=".popover-menu">one more popover</Link> massa at accumsan.
            Etiam purus odio, posuere in ligula vitae, viverra ultricies justo. Vestibulum nec
            interdum nisi. Aenean ac consectetur velit, non malesuada magna. Sed pharetra vehicula
            augue, vel venenatis lectus gravida eget. Curabitur lacus tellus, venenatis eu arcu in,
            interdum auctor nunc. Nunc non metus neque. Suspendisse viverra lectus sed risus
            aliquet, vel accumsan dolor feugiat.
          </p>
        </Block>
        <Popover className="popover-menu">
          <List>
            <ListItem link="#" popoverClose title="Dialog" />
            <ListItem link="#" popoverClose title="Tabs" />
            <ListItem link="#" popoverClose title="Side Panels" />
            <ListItem link="#" popoverClose title="List View" />
            <ListItem link="#" popoverClose title="Form Inputs" />
          </List>
        </Popover>
      </Page>
    </View>
  </App>
);

// src/pug/docs-demos/vue/popover.vue
<template>
    <f7-app>
      <f7-view main>
        <f7-page>
          <f7-navbar title="Popover"></f7-navbar>
          <f7-toolbar bottom>
            <f7-link>Dummy Link</f7-link>
            <f7-link popover-open=".popover-menu">Open Popover</f7-link>
          </f7-toolbar>

          <f7-block>
            <p><f7-button fill raised popover-open=".popover-menu">Open popover on me</f7-button></p>
            <p>Mauris fermentum neque et luctus venenatis. Vivamus a sem rhoncus, ornare tellus eu, euismod mauris. In porta turpis at semper convallis. Duis adipiscing leo eu nulla lacinia, quis rhoncus metus condimentum. Etiam nec malesuada nibh. Maecenas quis lacinia nisl, vel posuere dolor. Vestibulum condimentum, nisl ac vulputate egestas, neque enim dignissim elit, rhoncus volutpat magna enim a est. Aenean sit amet ligula neque. Cras suscipit rutrum enim. Nam a odio facilisis, elementum tellus non, <f7-link popover-open=".popover-menu">popover</f7-link> tortor. Pellentesque felis eros, dictum vitae lacinia quis, lobortis vitae ipsum. Cras vehicula bibendum lorem quis imperdiet.</p>
            <p>In hac habitasse platea dictumst. Etiam varius, ante vel ornare facilisis, velit massa rutrum dolor, ac porta magna magna lacinia nunc. Curabitur <f7-link popover-open=".popover-menu">popover!</f7-link> cursus laoreet. Aenean vel tempus augue. Pellentesque in imperdiet nibh. Mauris rhoncus nulla id sem suscipit volutpat. Pellentesque ac arcu in nisi viverra pulvinar. Nullam nulla orci, bibendum sed ligula non, ullamcorper iaculis mi. In hac habitasse platea dictumst. Praesent varius at nisl eu luctus. Cras aliquet porta est. Quisque elementum quis dui et consectetur. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sed laoreet purus. Pellentesque eget ante ante.</p>
            <p>Duis et ultricies nibh. Sed facilisis turpis urna, ac imperdiet erat venenatis eu. Proin sit amet faucibus tortor, et varius sem. Etiam vitae lacinia neque. Aliquam nisi purus, interdum in arcu sed, ultrices rutrum arcu. Nulla mi turpis, consectetur vel enim quis, facilisis viverra dui. Aliquam quis convallis tortor, quis semper ligula. Morbi ullamcorper <f7-link popover-open=".popover-menu">one more popover</f7-link> massa at accumsan. Etiam purus odio, posuere in ligula vitae, viverra ultricies justo. Vestibulum nec interdum nisi. Aenean ac consectetur velit, non malesuada magna. Sed pharetra vehicula augue, vel venenatis lectus gravida eget. Curabitur lacus tellus, venenatis eu arcu in, interdum auctor nunc. Nunc non metus neque. Suspendisse viverra lectus sed risus aliquet, vel accumsan dolor feugiat.</p>
          </f7-block>
          <f7-popover class="popover-menu">
            <f7-list>
              <f7-list-item link="#" popover-close title="Dialog"></f7-list-item>
              <f7-list-item link="#" popover-close title="Tabs"></f7-list-item>
              <f7-list-item link="#" popover-close title="Side Panels"></f7-list-item>
              <f7-list-item link="#" popover-close title="List View"></f7-list-item>
              <f7-list-item link="#" popover-close title="Form Inputs"></f7-list-item>
            </f7-list>
          </f7-popover>
        </f7-page>
      </f7-view>
    </f7-app>

</template>
