// src/pug/docs-demos/svelte/range-slider.svelte
<App>
  <View main>
    <Page>
      <Navbar title="Range Slider"></Navbar>

      <BlockTitle>Volume</BlockTitle>
      <List simpleList>
        <ListItem>
          <ListItemCell class="width-auto flex-shrink-0">
            <Icon ios="f7:speaker_fill" aurora="f7:speaker_fill" md="material:volume_mute"></Icon>
          </ListItemCell>
          <ListItemCell class="flex-shrink-3">
            <Range
              min={0}
              max={100}
              step={1}
              value={10}
            ></Range>
          </ListItemCell>
          <ListItemCell class="width-auto flex-shrink-0">
            <Icon ios="f7:speaker_3_fill" aurora="f7:speaker_3_fill" md="material:volume_up"></Icon>
          </ListItemCell>
        </ListItem>
      </List>

      <BlockTitle>Brightness</BlockTitle>
      <List simpleList>
        <ListItem>
          <ListItemCell class="width-auto flex-shrink-0">
            <Icon ios="f7:sun_min" aurora="f7:sun_min" md="material:brightness_low"></Icon>
          </ListItemCell>
          <ListItemCell class="flex-shrink-3">
            <Range
              min={0}
              max={100}
              step={1}
              value={50}
              label={true}
              color="orange"
            ></Range>
          </ListItemCell>
          <ListItemCell class="width-auto flex-shrink-0">
            <Icon ios="f7:sun_max_fill" aurora="f7:sun_max_fill" md="material:brightness_high"></Icon>
          </ListItemCell>
        </ListItem>
      </List>

      <BlockTitle class="display-flex justify-content-space-between">
        <span>Price Filter</span>
        <span>${priceMin} - ${priceMax}</span>
      </BlockTitle>
      <List simpleList>
        <ListItem>
          <ListItemCell class="width-auto flex-shrink-0">
            <Icon ios="f7:money_dollar_circle" aurora="f7:money_dollar_circle" md="material:attach_money"></Icon>
          </ListItemCell>
          <ListItemCell class="flex-shrink-3">
            <Range
              min={0}
              max={500}
              step={1}
              value={[priceMin, priceMax]}
              label={true}
              dual={true}
              color="green"
              onRangeChange={onPriceChange}
            ></Range>
          </ListItemCell>
          <ListItemCell class="width-auto flex-shrink-0">
            <Icon ios="f7:money_dollar_circle_fill" aurora="f7:money_dollar_circle_fill" md="material:monetization_on"></Icon>
          </ListItemCell>
        </ListItem>
      </List>

      <BlockTitle>With Scale</BlockTitle>
      <Block strong>
        <Range
          min={0}
          max={100}
          label={true}
          step={5}
          value={25}
          scale={true}
          scaleSteps={5}
          scaleSubSteps={4}
        />
      </Block>

      <BlockTitle>Vertical</BlockTitle>
      <Block strong class="display-flex justify-content-center">
        <Range
          class="margin-right"
          style="height: 160px"
          vertical={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={25}
        />
        <Range
          class="margin-horizontal"
          style="height: 160px"
          vertical={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={50}
        />
        <Range
          class="margin-horizontal"
          style="height: 160px"
          vertical={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={75}
        />
        <Range
          class="margin-left"
          style="height: 160px"
          dual={true}
          vertical={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={[25, 75]}
        />
      </Block>

      <BlockTitle>Vertical Reversed</BlockTitle>
      <Block strong class="display-flex justify-content-center">
        <Range
          class="margin-right"
          color="red"
          style="height: 160px"
          vertical={true}
          verticalReversed={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={25}
        />
        <Range
          class="margin-horizontal"
          color="red"
          style="height: 160px"
          vertical={true}
          verticalReversed={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={50}
        />
        <Range
          class="margin-horizontal"
          color="red"
          style="height: 160px"
          vertical={true}
          verticalReversed={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={75}
        />
        <Range
          class="margin-left"
          color="red"
          style="height: 160px"
          dual={true}
          vertical={true}
          verticalReversed={true}
          min={0}
          max={100}
          label={true}
          step={1}
          value={[25, 75]}
        />
      </Block>
    </Page>
  </View>
</App>

<script>
  import {App, View, Page, Navbar, BlockTitle, List, ListItem, ListItemCell, Icon, Range, Block} from 'framework7-svelte';

  let priceMin = 200;
  let priceMax = 400;

  function onPriceChange(values) {
    priceMin = values[0];
    priceMax = values[1];
  }
</script>

// src/pug/docs-demos/vue/range-slider.vue
<template>
  <f7-app>
    <f7-view main>
      <f7-page>
        <f7-navbar title="Range Slider"></f7-navbar>
        <f7-block-title>Volume</f7-block-title>
        <f7-list simple-list>
          <f7-list-item>
            <f7-list-item-cell
              class="flex-shrink-0"
              :style="{ width: theme.ios ? '28px' : theme.md ? '24px' : '18px' }"
            >
              <f7-icon
                ios="f7:speaker_fill"
                aurora="f7:speaker_fill"
                md="material:volume_mute"
              ></f7-icon>
            </f7-list-item-cell>
            <f7-list-item-cell class="flex-shrink-3">
              <f7-range :min="0" :max="100" :step="1" :value="10" />
            </f7-list-item-cell>
            <f7-list-item-cell
              class="flex-shrink-0"
              :style="{ width: theme.ios ? '28px' : theme.md ? '24px' : '18px' }"
            >
              <f7-icon
                ios="f7:speaker_3_fill"
                aurora="f7:speaker_3_fill"
                md="material:volume_up"
              ></f7-icon>
            </f7-list-item-cell>
          </f7-list-item>
        </f7-list>

        <f7-block-title>Brightness</f7-block-title>
        <f7-list simple-list>
          <f7-list-item>
            <f7-list-item-cell
              class="flex-shrink-0"
              :style="{ width: theme.ios ? '28px' : theme.md ? '24px' : '18px' }"
            >
              <f7-icon ios="f7:sun_min" aurora="f7:sun_min" md="material:brightness_low"></f7-icon>
            </f7-list-item-cell>
            <f7-list-item-cell class="flex-shrink-3">
              <f7-range :min="0" :max="100" :step="1" :value="50" :label="true" color="orange" />
            </f7-list-item-cell>
            <f7-list-item-cell
              class="flex-shrink-0"
              :style="{ width: theme.ios ? '28px' : theme.md ? '24px' : '18px' }"
            >
              <f7-icon
                ios="f7:sun_max_fill"
                aurora="f7:sun_max_fill"
                md="material:brightness_high"
              ></f7-icon>
            </f7-list-item-cell>
          </f7-list-item>
        </f7-list>

        <f7-block-title class="display-flex justify-content-space-between"
          >Price Filter <span>${{ priceMin }} - ${{ priceMax }}</span></f7-block-title
        >
        <f7-list simple-list>
          <f7-list-item>
            <f7-list-item-cell
              class="flex-shrink-0"
              :style="{ width: theme.ios ? '28px' : theme.md ? '24px' : '18px' }"
            >
              <f7-icon
                ios="f7:money_dollar_circle"
                aurora="f7:money_dollar_circle"
                md="material:attach_money"
              ></f7-icon>
            </f7-list-item-cell>
            <f7-list-item-cell class="flex-shrink-3">
              <f7-range
                :min="0"
                :max="500"
                :step="1"
                :value="[priceMin, priceMax]"
                :label="true"
                :dual="true"
                color="green"
                @range:change="onPriceChange"
              />
            </f7-list-item-cell>
            <f7-list-item-cell
              class="flex-shrink-0"
              :style="{ width: theme.ios ? '28px' : theme.md ? '24px' : '18px' }"
            >
              <f7-icon
                ios="f7:money_dollar_circle_fill"
                aurora="f7:money_dollar_circle_fill"
                md="material:monetization_on"
              ></f7-icon>
            </f7-list-item-cell>
          </f7-list-item>
        </f7-list>

        <f7-block-title>With Scale</f7-block-title>
        <f7-block strong>
          <f7-range
            :min="0"
            :max="100"
            :label="true"
            :step="5"
            :value="25"
            :scale="true"
            :scale-steps="5"
            :scale-sub-steps="4"
          />
        </f7-block>

        <f7-block-title>Vertical</f7-block-title>
        <f7-block strong class="display-flex justify-content-center">
          <f7-range
            class="margin-right"
            style="height: 160px"
            :vertical="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="25"
          />
          <f7-range
            class="margin-horizontal"
            style="height: 160px"
            :vertical="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="50"
          />
          <f7-range
            class="margin-horizontal"
            style="height: 160px"
            :vertical="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="75"
          />
          <f7-range
            class="margin-left"
            style="height: 160px"
            :dual="true"
            :vertical="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="[25, 75]"
          />
        </f7-block>

        <f7-block-title>Vertical Reversed</f7-block-title>
        <f7-block strong class="display-flex justify-content-center">
          <f7-range
            class="margin-right"
            color="red"
            style="height: 160px"
            :vertical="true"
            :vertical-reversed="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="25"
          />
          <f7-range
            class="margin-horizontal"
            color="red"
            style="height: 160px"
            :vertical="true"
            :vertical-reversed="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="50"
          />
          <f7-range
            class="margin-horizontal"
            color="red"
            style="height: 160px"
            :vertical="true"
            :vertical-reversed="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="75"
          />
          <f7-range
            class="margin-left"
            color="red"
            style="height: 160px"
            :dual="true"
            :vertical="true"
            :vertical-reversed="true"
            :min="0"
            :max="100"
            :label="true"
            :step="1"
            :value="[25, 75]"
          />
        </f7-block>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
<script>
import { theme } from 'framework7-vue';

export default {
  data() {
    return {
      theme,
      priceMin: 200,
      priceMax: 400,
    };
  },
  methods: {
    onPriceChange(values) {
      this.priceMin = values[0];
      this.priceMax = values[1];
    },
  },
};
</script>
