// src/pug/docs-demos/react/toolbar-tabbar.jsx
import React from 'react';
import { Page, Navbar, App, View, List, ListItem } from 'framework7-react';

import ToolbarPage from './toolbar-tabbar_toolbar.jsx';
import TabbarPage from './toolbar-tabbar_tabbar.jsx';
import TabbarLabelsPage from './toolbar-tabbar_tabbar-labels.jsx';
import TabbarScrollablePage from './toolbar-tabbar_tabbar-scrollable.jsx';
import ToolbarHidePage from './toolbar-tabbar_toolbar-hide-scroll.jsx';

const routes = [
  {
    path: '/toolbar/',
    component: ToolbarPage,
  },
  {
    path: '/tabbar/',
    component: TabbarPage,
  },
  {
    path: '/tabbar-labels/',
    component: TabbarLabelsPage,
  },
  {
    path: '/tabbar-scrollable/',
    component: TabbarScrollablePage,
  },
  {
    path: '/toolbar-hide-scroll/',
    component: ToolbarHidePage,
  },
];

export default () => (
  <App routes={routes}>
    <View main>
      <Page>
        <Navbar title="Toolbar & Tabbar" />
        <List>
          <ListItem link="/toolbar/" title="Toolbar" />
          <ListItem link="/tabbar/" title="Tabbar" />
          <ListItem link="/tabbar-labels/" title="Tabbar With Labels" />
          <ListItem link="/tabbar-scrollable/" title="Tabbar Scrollable" />
          <ListItem link="/toolbar-hide-scroll/" title="Hide Toolbar On Scroll" />
        </List>
      </Page>
    </View>
  </App>
);

// src/pug/docs-demos/vue/toolbar-tabbar.vue
<template>
  <f7-app :routes="routes">
    <f7-view main>
      <f7-page>
        <f7-navbar title="Toolbar & Tabbar"></f7-navbar>
        <f7-list>
          <f7-list-item link="/toolbar/" title="Toolbar"></f7-list-item>
          <f7-list-item link="/tabbar/" title="Tabbar"></f7-list-item>
          <f7-list-item link="/tabbar-labels/" title="Tabbar With Labels"></f7-list-item>
          <f7-list-item link="/tabbar-scrollable/" title="Tabbar Scrollable"></f7-list-item>
          <f7-list-item link="/toolbar-hide-scroll/" title="Hide Toolbar On Scroll"></f7-list-item>
        </f7-list>
      </f7-page>
    </f7-view>
  </f7-app>
</template>
<script>
  import ToolbarPage from './toolbar-tabbar_toolbar.svelte';
  import TabbarPage from './toolbar-tabbar_tabbar.svelte';
  import TabbarLabelsPage from './toolbar-tabbar_tabbar-labels.svelte';
  import TabbarScrollablePage from './toolbar-tabbar_tabbar-scrollable.svelte';
  import ToolbarHidePage from './toolbar-tabbar_toolbar-hide-scroll.svelte';

  export default {
    data() {
      return {
        routes: [
          {
            path: '/toolbar/',
            component: ToolbarPage,
          },
          {
            path: '/tabbar/',
            component: TabbarPage,
          },
          {
            path: '/tabbar-labels/',
            component: TabbarLabelsPage,
          },
          {
            path: '/tabbar-scrollable/',
            component: TabbarScrollablePage,
          },
          {
            path: '/toolbar-hide-scroll/',
            component: ToolbarHidePage,
          },
        ],
      };
    },
  }
</script>
