// src/pug/docs-demos/react/toolbar-tabbar_tabbar-scrollable.jsx
import React, { useState } from 'react';
import { Page, Navbar, Toolbar, Link, Block, NavRight, Tabs, Tab } from 'framework7-react';

export default () => {
  const [isBottom, setIsBottom] = useState(true);
  const tabs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  return (
    <Page pageContent={false}>
      <Navbar title="Tabbar Scrollable" backLink="Back">
        <NavRight>
          <Link
            iconIos="f7:arrow_up_arrow_down_circle_fill"
            iconMd="material:compare_arrows"
            onClick={() => setIsBottom(!isBottom)}
          ></Link>
        </NavRight>
      </Navbar>

      <Toolbar tabbar scrollable position={isBottom ? 'bottom' : 'top'}>
        {tabs.map((tab, index) => (
          <Link key={tab} tabLink={`#tab-${tab}`} tabLinkActive={index === 0}>
            Tab {tab}
          </Link>
        ))}
      </Toolbar>

      <Tabs>
        {tabs.map((tab, index) => (
          <Tab key={tab} id={`tab-${tab}`} className="page-content" tabActive={index === 0}>
            <Block>
              <p>
                <b>Tab {tab} content</b>
              </p>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam enim quia molestiae
                facilis laudantium voluptates obcaecati officia cum, sit libero commodi. Ratione
                illo suscipit temporibus sequi iure ad laboriosam accusamus?
              </p>
              <p>
                Saepe explicabo voluptas ducimus provident, doloremque quo totam molestias! Suscipit
                blanditiis eaque exercitationem praesentium reprehenderit, fuga accusamus possimus
                sed, sint facilis ratione quod, qui dignissimos voluptas! Aliquam rerum consequuntur
                deleniti.
              </p>
              <p>
                Totam reprehenderit amet commodi ipsum nam provident doloremque possimus odio
                itaque, est animi culpa modi consequatur reiciendis corporis libero laudantium sed
                eveniet unde delectus a maiores nihil dolores? Natus, perferendis.
              </p>
              <p>
                Atque quis totam repellendus omnis alias magnam corrupti, possimus aspernatur
                perspiciatis quae provident consequatur minima doloremque blanditiis nihil maxime
                ducimus earum autem. Magni animi blanditiis similique iusto, repellat sed quisquam!
              </p>
              <p>
                Suscipit, facere quasi atque totam. Repudiandae facilis at optio atque, rem nam,
                natus ratione cum enim voluptatem suscipit veniam! Repellat, est debitis. Modi nam
                mollitia explicabo, unde aliquid impedit! Adipisci!
              </p>
              <p>
                Deserunt adipisci tempora asperiores, quo, nisi ex delectus vitae consectetur iste
                fugiat iusto dolorem autem. Itaque, ipsa voluptas, a assumenda rem, dolorum porro
                accusantium, officiis veniam nostrum cum cumque impedit.
              </p>
              <p>
                Laborum illum ipsa voluptatibus possimus nesciunt ex consequatur rem, natus ad
                praesentium rerum libero consectetur temporibus cupiditate atque aspernatur, eaque
                provident eligendi quaerat ea soluta doloremque. Iure fugit, minima facere.
              </p>
            </Block>
          </Tab>
        ))}
      </Tabs>
    </Page>
  );
};

// src/pug/docs-demos/vue/toolbar-tabbar_tabbar-scrollable.vue
<template>
  <f7-page :page-content="false">
    <f7-navbar title="Tabbar Scrollable" back-link="Back">
      <f7-nav-right>
        <f7-link
          icon-ios="f7:arrow_up_arrow_down_circle_fill"
          icon-md="material:compare_arrows"
          @click="isBottom = !isBottom"
        ></f7-link>
      </f7-nav-right>
    </f7-navbar>
    <f7-toolbar tabbar scrollable :position="isBottom ? 'bottom' : 'top'">
      <f7-link
        v-for="(tab, index) in tabs"
        :key="tab"
        :tab-link="`#tab-${tab}`"
        :tab-link-active="index === 0"
        >Tab {{ tab }}</f7-link
      >
    </f7-toolbar>
    <f7-tabs>
      <f7-tab
        v-for="(tab, index) in tabs"
        :key="tab"
        :id="`tab-${tab}`"
        class="page-content"
        :tab-active="index === 0"
      >
        <f7-block>
          <p>
            <b>Tab {{ tab }} content</b>
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque corrupti, quos
            asperiores unde aspernatur illum odio, eveniet. Fugiat magnam perspiciatis ex
            dignissimos, rerum modi ea nesciunt praesentium iusto optio rem?
          </p>
          <p>
            Illo debitis et recusandae, ipsum nisi nostrum vero delectus quasi. Quasi, consequatur!
            Corrupti, explicabo maxime incidunt fugit sint dicta saepe officiis sed expedita, minima
            porro! Ipsa dolores quia, delectus labore!
          </p>
          <p>
            At similique minima placeat magni molestias sunt deleniti repudiandae voluptatibus
            magnam quam esse reprehenderit dolor enim qui sed alias, laboriosam quaerat laborum iure
            repellat praesentium pariatur dolorum possimus veniam! Consectetur.
          </p>
          <p>
            Sunt, sed, magnam! Qui, suscipit. Beatae cum ullam necessitatibus eligendi, culpa rem
            excepturi consequatur quidem totam eum voluptates nihil, enim pariatur incidunt corporis
            sed facere magni earum tenetur rerum ea.
          </p>
          <p>
            Veniam nulla quis molestias voluptatem inventore consectetur iusto voluptatibus
            perferendis quisquam, cupiditate voluptates, tenetur vero magnam nisi animi praesentium
            atque adipisci optio quod aliquid vel delectus ad? Dicta deleniti, recusandae.
          </p>
        </f7-block>
      </f7-tab>
    </f7-tabs>
  </f7-page>
</template>
<script>
export default {
  data() {
    return {
      tabs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      isBottom: true,
    };
  },
};
</script>
